---
title: "DGE_barplots"
author: "allyson_demerlis"
date: "2023-12-20"
output: html_document
---

Code from Rachel Alderice: https://github.com/RachelCAlderdice/CBASS_Nursery/blob/main/Differential_gene_expression.R

```{r}
load("Rdata_files/realModels_Pcli.RData")
library(DESeq2)
library(tidyverse)
```

Treated vs. Untreated
```{r}
Treatment_Treated_vs_Untreated=results(dds,contrast=c("Treatment","Treated","Untreated"), lfcThreshold = 0.0, alpha=0.05)
summary(Treatment_Treated_vs_Untreated, alpha=0.05)
results1 <- as.data.frame(subset(Treatment_Treated_vs_Untreated, Treatment_Treated_vs_Untreated$padj<0.05))
DE_up=subset(results1, results1$log2FoldChange > 0) 
DE_down=subset(results1, results1$log2FoldChange < 0) 
```

Treated vs. Initial
```{r}
Treatment_Treated_vs_Initial=results(dds,contrast=c("Treatment","Treated","Initial"), lfcThreshold = 0.0, alpha=0.05)
summary(Treatment_Treated_vs_Initial, alpha=0.05)
results2 <- as.data.frame(subset(Treatment_Treated_vs_Initial, Treatment_Treated_vs_Initial$padj<0.05))
DE_up=subset(results2, results2$log2FoldChange > 0) 
DE_down=subset(results2, results2$log2FoldChange < 0) 
```


Untreated vs. Initial
```{r}
Treatment_Untreated_vs_Initial=results(dds,contrast=c("Treatment","Untreated","Initial"), lfcThreshold = 0.0, alpha=0.05)
summary(Treatment_Untreated_vs_Initial, alpha=0.05)
results3 <- as.data.frame(subset(Treatment_Untreated_vs_Initial, Treatment_Untreated_vs_Initial$padj<0.05))
DE_up=subset(results3, results3$log2FoldChange > 0) 
DE_down=subset(results3, results3$log2FoldChange < 0) 
```

Manually create csv file in Excel of values for up and down genes and then read it into R
```{r}
DE<-read.csv("results_csv/DGE_barplot.csv")
DE$Regulation <- as.character(DE$Regulation)
DE$Group <- factor(DE$Group, levels=unique(DE$Group))
```


```{r}
ggplot(data = DE, aes(x = Group, y = genes, fill= Regulation))+
  geom_col(colour= "black", width= 0.8, size=0.9)+
  theme_classic()+
  scale_fill_manual(values=c("#666666", "#FFFFFF"))+
  theme(aspect.ratio = 1)+
  ylab(label="Genes")+
  xlab(label= "Group")+
  theme(legend.text=element_text(size=18))+
  theme(axis.text = element_text(size=18))+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust= 1))+
  theme(axis.title = element_text(size=22))+
  theme(text = element_text(size=20)) +
  theme(axis.line = element_line(colour = 'black', size = 1.5))+
  theme(axis.ticks = element_line(colour = "black", size = 1.5)) +
  theme(axis.ticks.length=unit(.25, "cm"))

ggsave("Barplot_DEG_regulation.pdf", dpi=300,width = 6, height = 8)
```

