---
title: "Pcli_PCA"
author: "allyson_demerlis"
date: "2023-11-24"
output: html_document
---

```{r}
library(DESeq2)
library(tidyverse)
library(factoextra)
library(cowplot)
library(limma)
library(ggforce)

load("RData_files/initial_fullddsdesigncountsVsdcountsWGCNA.RData")
```

# all data

```{r}
pca <- prcomp(t(assay(Vsd)))
summary(pca)
fviz_eig(pca)
```

Note: the data going into these PCAs is after the outlier removal step using arrayQualityMetrics
```{r}
plotPCA(Vsd, intgroup = c("Treatment"))
plotPCA(Vsd, intgroup = c("Genotype"))
plotPCA(Vsd, intgroup = c("Treatment", "Genotype"))

vst_PCAdata <- plotPCA(Vsd, intgroup = c("Treatment", "Genotype"), returnData = TRUE)
percentVar <- round(100*attr(vst_PCAdata, "percentVar")) 

g1 <- ggplot(vst_PCAdata, aes(PC1, PC2, color=Treatment, shape=Genotype)) +
   geom_point(size=3) +
   xlab(paste0("PC1: ",percentVar[1],"% variance")) +
   ylab(paste0("PC2: ",percentVar[2],"% variance")) +
   ggtitle("P. clivosa") +
   theme_classic() + #Set background color
   theme(panel.border = element_blank(), # Set border
         axis.line = element_line(colour = "black"), #Set axes color
         plot.background=element_blank()) +
  scale_color_manual(values = c("grey", "#00CCCC", "#FF3333"))
#ggsave("PCA_allgenets.pdf")

```


# separate genotype and plot treatment for each 

```{r}
#how do i make Vsd something that I can filter?
colData(Vsd)
metadata <- colData(Vsd)

A <- metadata$Genotype == "A"
A <- Vsd[, A]

vst_PCA_A <- plotPCA(A, intgroup = c("Treatment"), returnData = TRUE)
percentVar <- round(100*attr(vst_PCA_A, "percentVar")) 
# g2 <- ggplot(vst_PCA_A, aes(PC1, PC2, color=Treatment)) + 
#    geom_point(size=3) +
#    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
#    ylab(paste0("PC2: ",percentVar[2],"% variance")) +
#    ggtitle("P.clivosa colony A") +
#    theme_bw() + 
#    scale_color_manual(values = c("grey", "#00CCCC", "#FF3333"))

B <- metadata$Genotype == "B"
B <- Vsd[, B]

vst_PCA_B<- plotPCA(B, intgroup = c("Treatment"), returnData = TRUE)
percentVar <- round(100*attr(vst_PCA_B, "percentVar")) 
g3 <- ggplot(vst_PCA_B, aes(PC1, PC2, color=Treatment)) + 
   geom_point(size=3) +
   xlab(paste0("PC1: ",percentVar[1],"% variance")) +
   ylab(paste0("PC2: ",percentVar[2],"% variance")) +
   ggtitle("P.clivosa colony B") +
   theme_bw() + 
    scale_color_manual(values = c("grey", "#00CCCC", "#FF3333"))


C <- metadata$Genotype == "C"
C <- Vsd[, C]

vst_PCA_C<- plotPCA(C, intgroup = c("Treatment"), returnData = TRUE)
percentVar <- round(100*attr(vst_PCA_C, "percentVar")) 
g4 <- ggplot(vst_PCA_C, aes(PC1, PC2, color=Treatment)) + 
   geom_point(size=3) +
   xlab(paste0("PC1: ",percentVar[1],"% variance")) +
   ylab(paste0("PC2: ",percentVar[2],"% variance")) +
   ggtitle("P.clivosa colony C") +
   theme_bw() + 
    scale_color_manual(values = c("grey", "#00CCCC", "#FF3333"))


# combined_plot <- plot_grid(g1, g2, g3, g4, nrow = 2, ncol = 2)
# print(combined_plot)
# ggsave("combined_PCA_plot.pdf", combined_plot, width = 10, height = 7)
```


# PC axes 2 and 3
```{r}
## functions for PCA axes 2 and 3
#PCA 2 and 3 axis creation
pcaaxes23 = function (object, intgroup = "condition", ntop = 500, returnData = FALSE) 
{
    rv <- rowVars(assay(object))
    select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, 
        length(rv)))]
    pca <- prcomp(t(assay(object)[select, ]))
    percentVar <- pca$sdev^2/sum(pca$sdev^2)
    if (!all(intgroup %in% names(colData(object)))) {
        stop("the argument 'intgroup' should specify columns of colData(dds)")
    }
    intgroup.df <- as.data.frame(colData(object)[, intgroup, 
        drop = FALSE])
    group <- if (length(intgroup) > 1) {
        factor(apply(intgroup.df, 1, paste, collapse = ":"))
    }
    else {
        colData(object)[[intgroup]]
    }
    d <- data.frame(PC2 = pca$x[, 2], PC3 = pca$x[, 3], group = group, 
        intgroup.df, name = colnames(object))
    if (returnData) {
        attr(d, "percentVar") <- percentVar[2:3]
        return(d)
    }
    ggplot(data = d, aes_string(x = "PC2", y = "PC3", color = "group")) + 
        geom_point(size = 3) + xlab(paste0("PC2: ", round(percentVar[2] * 
        100), "% variance")) + ylab(paste0("PC3: ", round(percentVar[3] * 
        100), "% variance")) + coord_fixed()
}
```


```{r}
pca23 <- pcaaxes23(Vsd, intgroup=c("Treatment", "Genotype"), returnData = TRUE)

pcaaxes23(Vsd, intgroup=c("Genotype"), returnData = F)

pcaaxes23(Vsd, intgroup=c("Treatment"), returnData = F)

percentVar_pc23 <- round(100*attr(pca23, "percentVar")) 

ggplot(pca23, aes(PC2, PC3, color=Treatment)) + 
   geom_point(size=3) +
   xlab(paste0("PC2: ",percentVar_pc23[1],"% variance")) +
   ylab(paste0("PC3: ",percentVar_pc23[2],"% variance")) +
   ggtitle("Pclivosa") +
   theme_bw() + 
   #stat_ellipse(aes(PC2, PC3, group=time_point, lty=time_point), type = "norm") +
   #facet_wrap(~time_point) +
   scale_color_manual(values = c("grey", "#00CCCC", "#FF3333"))
```



# remove batch effect of genotype

```{r}
vsd2 <- removeBatchEffect(assay(Vsd), batch = Vsd$Genotype)

pca_result <- prcomp(t(vsd2))  # Transpose matrix because prcomp expects observations in rows

pca_summary<-summary(pca_result)

# Extract the proportion of variance explained by PC1 and PC2
percentVar_PC1 <- pca_summary$importance[2, "PC1"] * 100  # Proportion of variance for PC1
percentVar_PC2 <- pca_summary$importance[2, "PC2"] * 100  # Proportion of variance for PC2

# Round the percentages for better readability
percentVar_PC1_rounded <- round(percentVar_PC1)
percentVar_PC2_rounded <- round(percentVar_PC2)

# Create a data frame for ggplot
pca_data <- data.frame(PC1 = pca_result$x[,1], PC2 = pca_result$x[,2], Sample = rownames(pca_result$x))

design %>% 
  rownames_to_column("Sample") %>% 
full_join(pca_data, design, by = "Sample") -> pca_data

# Basic PCA plot
g2<-ggplot(pca_data, aes(x = PC1, y = PC2, label=NA, color = Treatment)) + 
   geom_point(size=3) +
   xlab(paste0("PC1: ",percentVar_PC1_rounded[1],"% variance")) +
   ylab(paste0("PC2: ",percentVar_PC2_rounded[1],"% variance")) +
   ggtitle("Pclivosa") +
   theme_classic() + 
   scale_color_manual(values = c("grey", "#00CCCC", "#FF3333"))
#ggsave("PCA_Pclivosa_removebatcheffect.pdf",  width = 10, height = 7)

#setting up data to add polygons
find_hull <- function(pca_data) pca_data[chull(pca_data$PC1, pca_data$PC2), ]
hulls <- ddply(pca_data, "Treatment", find_hull)

# Calculate group centroids for polygons
centroids <- pca_data %>%
  group_by(Treatment) %>%
  dplyr::summarise(PC1.mean = mean(PC1), PC2.mean = mean(PC2))

# Create the PCA plot
ggplot(pca_data, aes(x = PC1, y = PC2, color = Treatment)) +
  geom_point() +
  geom_polygon(data = hulls, alpha = 0.2, aes(color=Treatment, fill=Treatment)) +
  geom_point(aes(x=PC1.mean, y=PC2.mean,color=Treatment), data=centroids, show.legend=FALSE) +
  scale_fill_manual(values = c("grey", "#00CCCC", "#FF3333")) + 
  scale_color_manual(values = c("grey", "#00CCCC", "#FF3333")) + 
  xlab(paste0("PC1: ",percentVar_PC1_rounded[1],"% variance")) +
   ylab(paste0("PC2: ",percentVar_PC2_rounded[1],"% variance")) +
   ggtitle("Pclivosa") +
  theme_classic()


ggplot(pca_data, aes(x = PC1, y = PC2, color = Treatment)) +
  geom_point(size=3) +
  stat_ellipse(aes(PC1, PC2, group=Treatment, lty = Treatment), type = "norm") +
  scale_fill_manual(values = c("grey", "#00CCCC", "#FF3333")) + 
  scale_color_manual(values = c("grey", "#00CCCC", "#FF3333")) + 
  xlab(paste0("PC1: ",percentVar_PC1_rounded[1],"% variance")) +
   ylab(paste0("PC2: ",percentVar_PC2_rounded[1],"% variance")) +
   ggtitle("Pclivosa") +
  theme_classic() +
  theme(text = element_text(size = 15))
  
ggsave("PCA_Pclivosa_removebatcheffect_withellipses.pdf", width = 10, height = 7)
```

#combined plot of pre- and post- removing genotype as batch effect
```{r}
combined_plot <- plot_grid(g1, g2, g3, g4, nrow = 2, ncol = 2)
print(combined_plot)
ggsave("combined_PCA_plot_batcheffect.pdf", combined_plot, width = 10, height = 7)
```

