---
title: "FvFm"
author: "allyson_demerlis"
date: "2023-08-28"
output: html_document
---
# Packages

```{r}
library(tidyverse)
library(plotrix)
library(ggpubr)
library(rstatix)
library(cowplot)
library(car)
```


# Import data and create normalized dataset
```{r}
ipam_tidy_data <- read.csv("ipam_tidy_data.csv")

ipam_tidy_data %>% 
  dplyr::filter(!Treatment_period == "CBASS") %>%
  drop_na(Colony) %>% #this is because there are some corals that never matched up to IPAM values so they're just NA
  dplyr::mutate(Date = mdy(Date)) %>% 
  dplyr::select(Date, Colony, Puck, Tank, fvfm, Treatment, Species) %>% 
  dplyr::filter(fvfm < 0.75) %>% #filter out the outliers, 0.75 was set in Cunning et al 2021
  dplyr::filter(Date <= "2022-04-20") %>% 
  pivot_wider(names_from = Date, values_from = fvfm) %>% 
   mutate(fvfm_t0 = case_when(Species == "Acervicornis" ~ `2022-03-16`,
                                  Species == "Pclivosa" ~ `2022-03-21`)) %>% 
   mutate(fvfm_t1 = case_when(Species == "Acervicornis" ~ `2022-04-06`,
                                  Species == "Pclivosa" ~ `2022-04-06`)) %>% 
   mutate(fvfm_t2 = case_when(Species == "Acervicornis" ~ `2022-04-20`,
                                  Species == "Pclivosa" ~ `2022-04-20`)) %>% 
  mutate(t0 = fvfm_t0/fvfm_t0, t1 = fvfm_t1/fvfm_t0, t2 = fvfm_t2/fvfm_t0) %>% 
  pivot_longer(t0:t2, names_to = "fvfm_timepoint", values_to = "fvfm") %>% 
  mutate(numDays = case_when(fvfm_timepoint == "t0" ~ 0,
                             Species == "Pclivosa" & fvfm_timepoint == "t1" ~ 16,
                             Species == "Acervicornis" & fvfm_timepoint == "t1" ~ 21,
                             Species == "Pclivosa" & fvfm_timepoint == "t2" ~ 30,
                             Species == "Acervicornis" & fvfm_timepoint == "t2" ~ 35)) %>% 
  dplyr::select(!c(`2022-04-06`:`2022-04-20`)) -> ipam_norm_overtime

fvfm_norm_final <- ipam_norm_overtime %>% 
  select(Colony:Species, fvfm_timepoint, fvfm, numDays) %>% 
  filter(!fvfm_timepoint == "t1") #getting rid of day-7 time point for stats
```

# Acer
```{r}
p1<-fvfm_norm_final %>% 
  filter(Species == "Acervicornis") %>% 
  drop_na(fvfm) %>% 
  group_by(Treatment, Species, numDays) %>% 
  summarise(mean_fvfm = mean(fvfm), se_fvfm = std.error(fvfm)) %>% 
  ggplot(., aes(x=numDays, y=mean_fvfm, color = Treatment)) +
  scale_color_manual(labels=c("Variable", "Control"), values = c("#F54A34", "#60DBDB")) +
  geom_errorbar(aes(ymin = mean_fvfm - se_fvfm, ymax = mean_fvfm + se_fvfm), width = 0.2) +
  geom_point() +
  geom_line() +
  theme_classic() +
  labs(x="Days in Treatment", y="Fv/Fm", title = "A. cervicornis") +
  theme(text = element_text(size = 12)) 
```

## One-way ANOVA
```{r}
fvfm_norm_final %>% 
  filter(Species == "Acervicornis") %>% 
  filter(numDays == 35) -> fvfm_norm_Acer

fvfm_norm_Acer %>% 
  group_by(Treatment) %>% 
  summarise(count = n()) #variable=63 and control=70

summary(aov(fvfm ~ Treatment, data = fvfm_norm_Acer)) #significant

Acer_lm <- aov(fvfm ~ Treatment, data = fvfm_norm_Acer)
shapiro_test(Acer_lm$residuals) #not significant
leveneTest(fvfm ~ Treatment, data = fvfm_norm_Acer) #significant

#do welch's anova since variance is heteroschedastic
oneway.test(fvfm ~ Treatment, data = fvfm_norm_Acer, var.equal = FALSE) #significant
# F = 101.22, num df = 1.00, denom df = 115.99, p-value < 2.2e-16
```


# Pcli
```{r}
p2<-fvfm_norm_final %>% 
  filter(Species == "Pclivosa") %>% 
  drop_na(fvfm) %>% 
  group_by(Treatment, Species, numDays) %>% 
  summarise(mean_fvfm = mean(fvfm), se_fvfm = std.error(fvfm)) %>% 
  ggplot(., aes(x=numDays, y=mean_fvfm, color = Treatment)) +
  scale_color_manual(labels=c("Variable", "Control"), values = c("#F54A34", "#60DBDB")) +
  geom_errorbar(aes(ymin = mean_fvfm - se_fvfm, ymax = mean_fvfm + se_fvfm), width = 0.2) +
  geom_point() +
  geom_line() +
  theme_classic() +
  labs(x="Days in Treatment", y="Fv/Fm", title = "P. clivosa") +
  theme(text = element_text(size = 12)) 
```

## One-way ANOVA
```{r}
fvfm_norm_final %>% 
  filter(Species == "Pclivosa") %>% 
  filter(numDays == 30) -> fvfm_norm_Pcli

fvfm_norm_Pcli %>% 
  group_by(Treatment) %>% 
  summarise(count = n()) #variable=76 and control=73

summary(aov(fvfm ~ Treatment, data = fvfm_norm_Pcli)) #significant

Pcli_lm <- aov(fvfm ~ Treatment, data = fvfm_norm_Pcli)
shapiro_test(Pcli_lm$residuals) #not significant
leveneTest(fvfm ~ Treatment, data = fvfm_norm_Pcli) #significant

#do welch's anova since variance is heteroschedastic
oneway.test(fvfm ~ Treatment, data = fvfm_norm_Pcli, var.equal = FALSE) #significant
# F = 16.709, num df = 1.000, denom df = 95.163, p-value = 9.104e-05
```


# plot
```{r}
plot_grid(p1, p2, nrow=1,
       labels = c("A", "B"),       # Add panel labels
  label_size = 14)
ggsave("treatmentfvfm_bothspecies.pdf", width=10, height=5)
```