---
title: "specific_gene_expression"
author: "allyson_demerlis"
date: "2024-03-06"
output: html_document
---

# Acer 

## load libraries and data
```{r}
library(tidyverse)
library(DESeq2)
library(cowplot)

host_variable_genes <- read_csv("results_csv/host/host_variable_DEGs_annotated.csv")

load("Rdata_files/host/initial_fullddsdesigncountsVsdcounts.RData")
load("Rdata_files/host/vsd.RData")
```

## vst normalized counts
```{r}
metadata <- read_csv("../../physiology/metadata.csv") # this file has the corals labeled by their treatment, not time point of collection

metadata %>% 
  dplyr::select(Species, ID, Treatment) %>% 
  filter(Species == "Acropora cervicornis") %>% 
  dplyr::select(!Species) %>% 
  dplyr::rename(Sample_ID = ID) -> metadata

metadata$Formatted <- sprintf("Acer.%03d", metadata$Sample_ID)

metadata %>% 
  drop_na() %>%  
  dplyr::select(!Sample_ID) %>% 
  dplyr::rename(Sample_ID = Formatted) %>% 
  mutate(Treatment = case_when(Treatment == "Treated" ~ "Variable",
                               Treatment == "Untreated" ~ "Control")) -> metadata


# up regulated genes of interest
host_variable_genes %>% 
  arrange(desc(log2FoldChange))
# Acropora_031079 = chromatin assembly or disassembly 
#Acropora_023112 = histone H2A
#Acropora_34563 cytochrome P450

# downregulated genes of interest
# up regulated genes of interest
host_variable_genes %>% 
  arrange(log2FoldChange)
# Acropora_018568	peroxidase activity
# Acropora_019472	nitric-oxide synthase activity
# Acropora_003744	TNF receptor-associated factor

standard_error <- function(x) {
  sd(x) / sqrt(length(x))
}
```

## all genes of interest for host
```{r}
p1<-t(vsd) %>% 
  as.data.frame() %>% 
  dplyr::select(Acropora_019472, Acropora_023112, Acropora_018568) %>% 
  rownames_to_column() %>% 
  separate(rowname, into = c("Sample_ID", "Genotype", "Expression", "Treatment"), sep ="_") %>% 
  unite("Genotype", Genotype,Expression, sep = "_") %>% 
  mutate(Day = case_when(Treatment == "Initial" ~ 0,
                         Treatment == "Variable" ~ 28,
                         Treatment == "Control" ~ 28)) %>% 
  dplyr::select(!Treatment) %>% 
  full_join(., metadata) %>% 
  drop_na() %>% 
  pivot_longer(Acropora_019472:Acropora_018568, names_to = "Gene", values_to = "Vst-normalized expression") %>% 
  group_by(Day, Treatment, Gene) %>% 
  mutate(mean_expression = mean(`Vst-normalized expression`), se = standard_error(`Vst-normalized expression`)) %>% 
  ggplot(., aes(x=Day, y=mean_expression, color = Treatment, fill = Treatment)) +
  geom_point(alpha=0.2) +
  geom_errorbar(aes(ymin = mean_expression - se, ymax = mean_expression + se), width = 0.1) +
  theme_classic() +
  geom_smooth(method = "lm", mapping = aes(color = Treatment), se=FALSE) +
  scale_color_manual(values = c("#00CCCC", "#FF3333"))+
  labs(y = "Vst-Normalized Expression Level", title = "Acropora cervicornis") +
  theme(text = element_text(size = 13))+
  facet_wrap(~Gene)
```

# Symbiodinium

## load data
```{r}
sym_variable_genes <- read_csv("results_csv/symbiont/sym_Variable_genes_annot.csv")

load("Rdata_files/symbiont/Sym_initial_fullddsdesigncountsVsdcounts.RData")
load("Rdata_files/symbiont/vsd.RData")
```



## vst normalized counts
```{r}
metadata <- read_csv("../../physiology/metadata.csv") # this file has the corals labeled by their treatment, not time point of collection

metadata %>% 
  dplyr::select(Species, ID, Treatment) %>% 
  filter(Species == "Acropora cervicornis") %>% 
  dplyr::select(!Species) %>% 
  dplyr::rename(Sample_ID = ID) -> metadata

metadata$Formatted <- sprintf("Acer.%03d", metadata$Sample_ID)

metadata %>% 
  drop_na() %>%  
  dplyr::select(!Sample_ID) %>% 
  dplyr::rename(Sample_ID = Formatted) %>% 
  mutate(Treatment = case_when(Treatment == "Treated" ~ "Variable",
                               Treatment == "Untreated" ~ "Control")) -> metadata


# up regulated genes of interest
sym_variable_genes %>%
  arrange(desc(log2FoldChange)) %>% view()
# Symbiodinium13325 = Mediates cleavage of dimethlysulfonioproprionate 
#Symbiodinium18242 oxidoreductase activity
#Symbiodinium75213 antioxidant activity
# 	Symbiodinium27195 Cytochrome c oxidase

# downregulated genes of interest
sym_variable_genes %>% 
  arrange(log2FoldChange) %>% view()
# none

standard_error <- function(x) {
  sd(x) / sqrt(length(x))
}
```

## all genes of interest for symbiont
```{r}
p2<-t(vsd) %>% 
  as.data.frame() %>% 
  dplyr::select(Symbiodinium13325, Symbiodinium18242, Symbiodinium75213) %>% 
  rownames_to_column() %>% 
  separate(rowname, into = c("Sample_ID", "Genotype", "Expression", "Treatment"), sep ="_") %>% 
  unite("Genotype", Genotype,Expression, sep = "_") %>% 
  mutate(Day = case_when(Treatment == "Initial" ~ 0,
                         Treatment == "Variable" ~ 28,
                         Treatment == "Control" ~ 28)) %>% 
  dplyr::select(!Treatment) %>% 
  full_join(., metadata) %>% 
  drop_na() %>% 
  pivot_longer(Symbiodinium13325:Symbiodinium75213, names_to = "Gene", values_to = "Vst-normalized expression") %>% 
  group_by(Day, Treatment, Gene) %>% 
  mutate(mean_expression = mean(`Vst-normalized expression`), se = standard_error(`Vst-normalized expression`)) %>% 
  ggplot(., aes(x=Day, y=mean_expression, color = Treatment, fill = Treatment)) +
  geom_point(alpha=0.2) +
  geom_errorbar(aes(ymin = mean_expression - se, ymax = mean_expression + se), width = 0.1) +
  theme_classic() +
  geom_smooth(method = "lm", mapping = aes(color = Treatment), se=FALSE) +
  scale_color_manual(values = c("#00CCCC", "#FF3333"))+
  labs(y = "Vst-Normalized Expression Level", title = "Symbiodinium spp.") +
  theme(text = element_text(size = 13))+
  facet_wrap(~Gene)
```

# join plots
```{r}
cowplot::plot_grid(p1, p2, ncol = 1)
#ggsave("Acer_host_sym_specificgenes.pdf", width = 7, height = 5)
```





