---
title: "Acer_VolcanoPlot"
author: "allyson_demerlis"
date: "2023-09-16"
output: html_document
---

```{r}
library(EnhancedVolcano)
library(tidyverse)
```


```{r}
load("../RData_files/pvals.RData")
```


Treated vs. Initial
```{r}
Treated_vs_Initial_annotated <- as.data.frame(Treatment_Treated_vs_Initial) %>%
  rownames_to_column(var="gene") %>% 
  left_join(read.table(file = "bioinformatics/Acervicornis_iso2geneName.tab",
                       sep = "\t",
                       quote="", fill=FALSE) %>%
              mutate(gene = V1,
                     annot = V2) %>%
              dplyr::select(-V1, -V2), by = c("gene" = "gene"))
str(Treated_vs_Initial_annotated) #25003 x 8

  keyvals <- ifelse(
    Treated_vs_Initial_annotated$log2FoldChange < 0 & Treated_vs_Initial_annotated$padj < 0.05, 'royalblue',
      ifelse(Treated_vs_Initial_annotated$log2FoldChange > 0 & Treated_vs_Initial_annotated$padj < 0.05, 'red',
        'grey'))
  keyvals[is.na(keyvals)] <- 'grey'
  names(keyvals)[keyvals == 'red'] <- 'significantly high (padj < 0.05 and L2FC > 0)'
  names(keyvals)[keyvals == 'grey'] <- 'L2FC=0 and padj > 0.05'
  names(keyvals)[keyvals == 'royalblue'] <- 'significantly low (padj < 0.05 and L2FC < 0)'

pdf(file="volcano_Treated_vs_Initial.pdf", width = 12, height = 6)  
  EnhancedVolcano(Treated_vs_Initial_annotated,
    lab = NA,
    title = "Treated vs. Initial",
    x = 'log2FoldChange',
    y = 'padj',
    ylab = bquote(~-Log[10]~ 'FDR P-adjusted'),
    legendPosition = 'right',
    pCutoff = 10e-2,
    FCcutoff = 0.25,
    legendIconSize = 5.0,
    labSize = 6.0,
    colCustom = keyvals,
    colAlpha = 0.5) 
```


Treated vs. Untreated
```{r}
Treated_vs_Untreated_annotated <- as.data.frame(Treatment_Treated_vs_Untreated) %>%
  rownames_to_column(var="gene") %>% 
  left_join(read.table(file = "../bioinformatics/Acervicornis_iso2geneName.tab",
                       sep = "\t",
                       quote="", fill=FALSE) %>%
              mutate(gene = V1,
                     annot = V2) %>%
              dplyr::select(-V1, -V2), by = c("gene" = "gene")) 

keyvals <- ifelse(
    Treated_vs_Untreated_annotated$log2FoldChange < 0 & Treated_vs_Untreated_annotated$padj < 0.05, '#00CCCC',
      ifelse(Treated_vs_Untreated_annotated$log2FoldChange > 0 & Treated_vs_Untreated_annotated$padj < 0.05, '#FF3333',
        'grey'))
  keyvals[is.na(keyvals)] <- 'grey'
  names(keyvals)[keyvals == '#FF3333'] <- 'significantly high (padj < 0.05 and L2FC > 0)'
  names(keyvals)[keyvals == 'grey'] <- 'L2FC=0 and padj > 0.05'
  names(keyvals)[keyvals == '#00CCCC'] <- 'significantly low (padj < 0.05 and L2FC < 0)'

pdf(file="volcano_Treated_vs_Untreated.pdf", width = 12, height = 6)  
  EnhancedVolcano(Treated_vs_Untreated_annotated,
    lab = NA,
    title = "Treated vs. Untreated",
    x = 'log2FoldChange',
    y = 'padj',
    ylab = bquote(~-Log[10]~ 'FDR P-adjusted'),
    legendPosition = 'right',
    pCutoff = 10e-2,
    FCcutoff = 0.25,
    legendIconSize = 5.0,
    labSize = 6.0,
   colCustom = keyvals,
    colAlpha = 0.5)
```


Untreated vs. Initial 
```{r}
Untreated_vs_Initial_annotated <- as.data.frame(Treatment_Untreated_vs_Initial) %>%
  rownames_to_column(var="gene") %>% 
  left_join(read.table(file = "bioinformatics/Acervicornis_iso2geneName.tab",
                       sep = "\t",
                       quote="", fill=FALSE) %>%
              mutate(gene = V1,
                     annot = V2) %>%
              dplyr::select(-V1, -V2), by = c("gene" = "gene"))

keyvals <- ifelse(
    Untreated_vs_Initial_annotated$log2FoldChange < 0 & Untreated_vs_Initial_annotated$padj < 0.05, 'royalblue',
      ifelse(Untreated_vs_Initial_annotated$log2FoldChange > 0 & Untreated_vs_Initial_annotated$padj < 0.05, 'red',
        'grey'))
  keyvals[is.na(keyvals)] <- 'grey'
  names(keyvals)[keyvals == 'red'] <- 'significantly high (padj < 0.05 and L2FC > 0)'
  names(keyvals)[keyvals == 'grey'] <- 'L2FC=0 and padj > 0.05'
  names(keyvals)[keyvals == 'royalblue'] <- 'significantly low (padj < 0.05 and L2FC < 0)'

pdf(file="volcano_Untreated_vs_Initial.pdf", width = 12, height = 6)  
  EnhancedVolcano(Untreated_vs_Initial_annotated,
    title = "Untreated vs. Initial",
    lab = NA,
    x = 'log2FoldChange',
    y = 'padj',
    ylab = bquote(~-Log[10]~ 'FDR P-adjusted'),
    legendPosition = 'right',
    pCutoff = 10e-2,
    FCcutoff = 0.25,
    legendIconSize = 5.0,
    labSize = 6.0,
   colCustom = keyvals,
    colAlpha = 0.5)
```


only the genes uniquely expressed in treated vs untreated (should be 116 genes)
```{r}
unique_TU <- read_csv("../results_csv/unique_Treated_vs_Untreated_annotated.csv")

as.data.frame(Treatment_Treated_vs_Untreated) %>%
  rownames_to_column(var="gene") %>% 
  right_join(., unique_TU) -> unique_TU_allinfo

keyvals <- ifelse(
    unique_TU_allinfo$log2FoldChange < 0 & unique_TU_allinfo$padj < 0.05, 'royalblue',
      ifelse(unique_TU_allinfo$log2FoldChange > 0 & unique_TU_allinfo$padj < 0.05, 'red',
        'grey'))
  keyvals[is.na(keyvals)] <- 'grey'
  names(keyvals)[keyvals == 'red'] <- 'significantly high (padj < 0.05 and L2FC > 0)'
  names(keyvals)[keyvals == 'grey'] <- 'L2FC=0 and padj > 0.05'
  names(keyvals)[keyvals == 'royalblue'] <- 'significantly low (padj < 0.05 and L2FC < 0)'

pdf(file="volcano_Treated_vs_Untreated_unique.pdf", width = 12, height = 6)  
  EnhancedVolcano(unique_TU_allinfo,
    title = "Treated vs. Untreated",
    lab = NA,
    x = 'log2FoldChange',
    y = 'padj',
    ylab = bquote(~-Log[10]~ 'FDR P-adjusted'),
    legendPosition = 'right',
    pCutoff = 10e-2,
    FCcutoff = 0.25,
    legendIconSize = 5.0,
    labSize = 6.0,
   colCustom = keyvals,
    colAlpha = 0.5)
```


