---
title: "PcaGrid"
author: "allyson_demerlis"
date: "2024-12-02"
output: html_document
---

# Installing and loading packages
```{r}
# if (!requireNamespace("BiocManager", quietly = TRUE))
#   install.packages("BiocManager")
# BiocManager::install(version = "3.15")
# BiocManager::install("DESeq2",dependencies=T)
# BiocManager::install("BiocParallel")

# install.packages("pheatmap")
# install.packages("VennDiagram")
# install.packages("gplots")
# install.packages("vegan")
# install.packages("plotrix")
# install.packages("ape")
# install.packages("ggplot2")
# install.packages("rrcov")

library(DESeq2)
library(tidyverse)
library(ape)
library(vegan)
library(rrcov)
```

# Read in counts matrix and initial tidying
```{r}
#read in counts
counts = read.delim("final_counts_matrix.txt")

#select only Acropora genes, remove Symbiodinium
counts <- counts %>% filter(!grepl("^Symbiodinium[0-9]+$", X))

column_to_rownames(counts, var ="X") -> counts
counts %>% 
  select(!X.1) -> counts

#two of the sample IDs are in all caps, need to change it to be "Acer"
counts <- counts %>% dplyr::rename(Acer.112 = ACER.112)
counts <- counts %>% dplyr::rename(Acer.124 = ACER.124)
 
# how many genes we have total?
nrow(counts) #30122
ncol(counts) #48 samples

# how does the data look? 
head(counts)

colnames(counts) # sample IDs (i.e. Acer.005). You need to keep track of column names and row names of data frames throughout this analysis because they MUST MATCH 
rownames(counts) #gene names (but not actual gene names, arbitrary gene names like Acropora000001. To get "actual" gene names, need annotation files)
```

## filtering out low-count genes
```{r}
keep <- rowSums(counts) >= 10 #less than 10 counts across all samples
countData <- counts[keep,]
nrow(countData) #25003
ncol(countData) #48
#write.csv(countData, file = "Acer_countdata.csv")
```

## import and tidy design file
```{r}
# importing a design .csv file
design = read.csv("../treatment_metadata.csv", head=TRUE)

design %>% 
  filter(Species == "Acer") -> design

design %>% 
  select(!Species) -> design

column_to_rownames(design, var="Sample_ID") -> design
design$Genotype <- as.factor(design$Genotype)
design$Genotype <- factor(gsub("-", "_", design$Genotype)) #DESeq2 does not like hyphens in factor names
design$Treatment <- as.factor(design$Treatment)
design$Geno_Treatment <- interaction(design$Genotype, design$Treatment)

# check if order is the same
all(rownames(design) == colnames(countData))
#TRUE
```


# DESeq2 full model design
```{r}
#when making dds formula, the order of variables in the design matters. The design indicates how to model the samples, (here: design = ~batch + condition), that we want to measure the effect of the condition, controlling for batch differences. The two factor variables batch and condition should be columns of coldata.

dds = DESeqDataSetFromMatrix(countData=countData, colData=design, design=~ Genotype + Treatment)
dds=estimateSizeFactors(dds)
plot(sort(sizeFactors(dds))) 


dds = DESeqDataSetFromMatrix(countData=countData, colData=design, design= ~Geno_Treatment)
dds=estimateSizeFactors(dds)
plot(sort(sizeFactors(dds))) 

dds=DESeq(dds)

par(mar=c(8,5,2,2))
boxplot(log10(assays(dds)[["cooks"]]), range=0, las=2)

totalCountshost=colSums(countData)
totalCountshost
barplot(totalCountshost)

min(totalCountshost) 
max(totalCountshost) 

# Create the boxplot
boxplot(log10(countData + 1), 
        main = "Log10 Counts per Gene", 
        ylab = "Log10(Counts + 1)", 
        las = 2,  # Rotate labels to vertical
        cex.axis = 0.8)  # Adjust font size

total_counts_per_gene <- rowSums(countData)
hist(total_counts_per_gene, 
     main = "Histogram of Total Counts Per Gene", 
     xlab = "Counts", 
     col = "lightgreen")
```

## variance stabilized transformation for visualization
```{r}
# for large datasets, rlog may take too much time, especially for an unfiltered dataframe
# vsd is much faster and still works
Vsd=varianceStabilizingTransformation(dds, blind = FALSE)

rlogged = rlogTransformation(dds, blind = FALSE)
```

### PCA
```{r}
DESeq2::plotPCA(Vsd, intgroup=c("Treatment", "Genotype"))

DESeq2::plotPCA(rlogged, intgroup=c("Treatment", "Genotype"))
```

### robust PCA for outlier detection
```{r}
#following https://github.com/China2302/3_prime_RNAseq_O.faveolata/blob/main/04_normalization.Rmd

rpca1 <- PcaGrid(t(assay(rlogged)), k=3, scale=FALSE)

plot(rpca1)

rpca2 <- PcaGrid(t(assay(Vsd)), k=3, scale=FALSE)

plot(rpca2)

rpca3 <- PcaHubert(t(assay(Vsd)))
plot(rpca3)
```