---
title: "florida_map_sties"
author: "allyson_demerlis"
date: "2023-11-06"
output: html_document
---

```{r}
library(ggplot2)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(ggspatial)
library(raster)

oceanbottom <- raster("~/Downloads/OB_LR/OB_LR.tif")
bathymetry_df <- as.data.frame(oceanbottom, xy = TRUE)
str(bathymetry_df)
```

```{r}
world <- ne_countries(scale = 110, returnclass = "sf") #this requires the high-res package "raturalearthhires"

#input coordinates where Acer and Pcli were collected 

sites <- st_as_sf(data.frame(longitude = c(-80.0987, -80.15235), latitude = c(25.6763, 
    25.77044)), coords = c("longitude", "latitude"), crs = 4326, 
agr = "constant")

(florida <- ggplot(data = world) +
     geom_sf(fill = "grey") +
     geom_sf(data = sites, size = 4, shape = 23, fill = "darkred") +
     coord_sf(xlim = c(-87.35, -79.5), ylim = c(24.1, 30.8)) +
     xlab("Longitude")+ ylab("Latitude")+
     theme(panel.grid.major = element_line(colour = gray(0.9), linetype = "dashed", 
         size = 0.5), panel.background = element_rect(fill = "aliceblue"), 
          panel.border = element_rect(fill = NA)) )
      # geom_raster(data = bathymetry_df, aes(x = x, y = y)))

(siteA <- ggplot(data = world) +
     geom_sf(fill = "grey") +
     geom_sf(data = sites, size = 4, shape = 23, fill = "darkred") +
     coord_sf(xlim = c(-79.5, -80.5), ylim = c(26, 
    25)) + 
    xlab("Longitude")+ ylab("Latitude")+
     annotate("text", x = -80.18, y = 26.92, label= "Emerald Reef", size = 6) + 
     theme(panel.grid.major = element_line(colour = gray(0.5), linetype = "dashed", 
         size = 0.5), panel.background = element_rect(fill = "aliceblue"), 
         panel.border = element_rect(fill = NA)))
```

