---
title: "immunecellassay_take2"
author: "allyson_demerlis"
date: "2024-03-21"
output: html_document
---

# Load libraries and datasets
```{r}
library(tidyverse)
library(plotrix)
library(ggpubr)
library(rstatix)
library(cowplot)
library(dunn.test)
library(Rmisc)
library(plyr)
library(dplyr)

percent_cells_df <- read_csv("Grace_percentcells_alldata.csv") 

percent_cells_df%>% 
    mutate(Treatment = case_when(Treatment == "Control" ~ "Untreated",
                               Treatment == "Variable" ~ "Treated")) -> percent_cells_df

#there's one outlier to remove right off the bat: T1	Pcli	B	P9	r2	Percent=111.50	T1	Untreated
percent_cells_df %>% 
  filter(!(TimePoint=="T1" & Species == "Pcli" & Genotype == "B" & Treatment == "Untreated" & ID == "P9" & Replicate == "r2")) -> percent_cells_df

#replicates are technical replicates of the same coral fragment
#time points:
#T0 = initial pre-treatment (March 22)
#T1 = one week into treatment (March 30)
#T2 = end of treatment (April 20)
#follow-up = post CBASS and treatment follow-up (June 1)

percent_cells_df %>% 
  mutate(num_days = case_when(TimePoint == "T0" ~ "0",
                              TimePoint == "T1" ~ "7",
                              TimePoint == "T2" ~ "28",
                              TimePoint == "FollowUp" ~ "71")) %>% 
  mutate(num_days = as.factor(num_days)) %>% 
  mutate(num_days = fct_relevel(num_days, "0", "7", "28", "71")) -> percent_cells_df
```


# calculate percent change for day 28 to day 0
```{r}
percent_cells_df %>% 
  drop_na() %>% #one technical replicate is NA for one coral ID
  group_by(num_days, Species, Genotype, ID, Treatment) %>% 
  dplyr::mutate(mean_replicate_percent_perID = mean(Percent)) %>% 
  ungroup() %>% 
  group_by(num_days, Species, Genotype, Treatment) %>% 
  dplyr::mutate(mean_replicate_percent_perGenet = mean(Percent)) %>% 
  select(Species, Genotype, Tank, Treatment, num_days, mean_replicate_percent_perGenet) %>% 
  distinct() %>% 
  filter(num_days == "0" | num_days == "28") %>% 
  pivot_wider(names_from = "num_days", values_from = "mean_replicate_percent_perGenet") %>% 
  mutate(relative_activity = ((`28`-`0`)/`0`)*100) %>% #T1-T0/T0*100
  ggplot(., aes(x=Species, y=relative_activity, fill= Treatment)) +
  geom_boxplot() +
  scale_fill_manual(labels=c("Treated", "Untreated"), values = c("#F54A34", "#60DBDB")) +
  ylab("% Decline Immune Cell Activity")+
  theme_classic() +
  theme(text = element_text(size = 15)) 
```

### Statistics

Change to factors
```{r}
percent_cells_df %>% 
  drop_na() %>% #one technical replicate is NA for one coral ID
  group_by(num_days, Species, Genotype, ID, Treatment) %>% 
  dplyr::mutate(mean_replicate_percent_perID = mean(Percent)) %>% 
  ungroup() %>% 
  group_by(num_days, Species, Genotype, Treatment) %>% 
  dplyr::mutate(mean_replicate_percent_perGenet = mean(Percent)) %>% 
  select(Species, Genotype, Tank, Treatment, num_days, mean_replicate_percent_perGenet) %>% 
  distinct() %>% 
  filter(num_days == "0" | num_days == "28") %>% 
  pivot_wider(names_from = "num_days", values_from = "mean_replicate_percent_perGenet") %>% 
  mutate(relative_activity = ((`28`-`0`)/`0`)*100) -> percent_cells_speciestreatments
```

Create linear model to test normality of residuals and homogeneity of variance. Remove outliers
```{r}
treat_model <- lm(relative_activity ~ Treatment*Species + Genotype, data = percent_cells_speciestreatments)
treat_model_metrics <- augment(treat_model)
plot(treat_model)

# assess normality of residuals using Shapiro-Wilk test
shapiro_test(treat_model_metrics$.resid) # not significant

# assess homogeneity of variances using Levene's Test
levene_test(.resid ~ Treatment*Species, data = treat_model_metrics) #not significant

# identifying outliers
treat_model_metrics %>% 
  filter(abs(.std.resid) > 3)
# 0 outliers

#run two-way anova
aov(relative_activity ~ Treatment*Species, data = percent_cells_speciestreatments)

summary(aov(relative_activity ~ Treatment*Species, data = percent_cells_speciestreatments))

TukeyHSD(aov(relative_activity ~ Treatment*Species, data = percent_cells_speciestreatments))
```
