---
title: "Acer_PCA"
author: "allyson_demerlis"
date: "2023-08-24"
output: html_document
---

```{r}
library(DESeq2)
library(tidyverse)
library(factoextra)

load("RData_files/initial_fullddsdesigncountsVsdcountsWGCNA.RData")
```


```{r}
pca <- prcomp(t(assay(Vsd)))
summary(pca)
fviz_eig(pca)
```


```{r}
plotPCA(Vsd, intgroup = c("Treatment"))
plotPCA(Vsd, intgroup = c("Genotype"))
plotPCA(Vsd, intgroup = c("time_point"))
plotPCA(Vsd, intgroup = c("Treatment", "Genotype", "time_point"))

vst_PCAdata <- plotPCA(Vsd, intgroup = c("Treatment", "Genotype", "time_point"), returnData = TRUE)
percentVar <- round(100*attr(vst_PCAdata, "percentVar")) 

ggplot(vst_PCAdata, aes(PC1, PC2, color=Treatment, shape=Genotype)) + 
   geom_point(size=3) +
   xlab(paste0("PC1: ",percentVar[1],"% variance")) +
   ylab(paste0("PC2: ",percentVar[2],"% variance")) +
   ggtitle("P. clivosa") +
   theme_bw() + #Set background color
   theme(panel.border = element_blank(), # Set border
         axis.line = element_line(colour = "black"), #Set axes color
         plot.background=element_blank()) + 
  stat_ellipse(aes(PC1, PC2, group=time_point, lty = time_point), type = "norm")

plotPCA(Vsd, intgroup = c("Treatment","time_point"))

vst_nogeno_PCAdata <- plotPCA(Vsd, intgroup = c("Treatment","time_point"), returnData = TRUE)
percentVar <- round(100*attr(vst_nogeno_PCAdata, "percentVar"))
ggplot(vst_nogeno_PCAdata, aes(PC1, PC2, color=group, shape=Treatment)) + 
   geom_point(size=3) +
   xlab(paste0("PC1: ",percentVar[1],"% variance")) +
   ylab(paste0("PC2: ",percentVar[2],"% variance")) +
   ggtitle("P. clivosa") +
   theme_bw() +
  stat_ellipse(aes(PC1, PC2, group=group, lty = time_point), type = "norm") +
  scale_color_manual(values = c("#00CCCC","#33CCCC", "#FF6633", "#FF3333"))

ggplot(vst_nogeno_PCAdata, aes(PC1, PC2, color=group)) + 
   geom_point(size=3) +
   xlab(paste0("PC1: ",percentVar[1],"% variance")) +
   ylab(paste0("PC2: ",percentVar[2],"% variance")) +
   ggtitle("P. clivosa") +
   theme_bw() +
  scale_color_manual(values = c("#00CCCC","#33CCCC", "#FF6633", "#FF3333"))
```

