---
title: "Acer_PCA"
author: "allyson_demerlis"
date: "2023-08-24"
output: html_document
---

# load libraries and data
```{r}
library(DESeq2)
library(tidyverse)
library(factoextra)
library(plyr)
library(dplyr)

load("RData_files/initial_fullddsdesigncountsVsdcountsWGCNA.RData")
```

# create pca object from vst of dds object
```{r}
pca <- prcomp(t(assay(Vsd)), scale = TRUE, center=TRUE)
summary(pca)
fviz_eig(pca)
```


# Plotting everything together
```{r}
plotPCA(Vsd, intgroup = c("Treatment"))
plotPCA(Vsd, intgroup = c("Genotype"))
plotPCA(Vsd, intgroup = c("time_point"))
plotPCA(Vsd, intgroup = c("Treatment", "Genotype", "time_point"))

vst_PCAdata <- plotPCA(Vsd, intgroup = c("Treatment", "Genotype", "time_point"), returnData = TRUE)
percentVar <- round(100*attr(vst_PCAdata, "percentVar")) 

ggplot(vst_PCAdata, aes(PC1, PC2, color=Treatment, shape=Genotype)) + 
   geom_point(size=3) +
   xlab(paste0("PC1: ",percentVar[1],"% variance")) +
   ylab(paste0("PC2: ",percentVar[2],"% variance")) +
   ggtitle("A. cervicornis") +
   theme_bw() + #Set background color
   theme(panel.border = element_blank(), # Set border
         axis.line = element_line(colour = "black"), #Set axes color
         plot.background=element_blank()) + 
  stat_ellipse(aes(PC1, PC2, group=time_point, lty = time_point), type = "norm")
```

# separate genotypes and plot treatment and time for each
```{r}
vst_PCA_SIC <- vst_PCAdata %>% 
  filter(Genotype == "SI-C")

vst_PCA_MBB <- vst_PCAdata %>% 
  filter(Genotype == "MB-B")

vst_PCA_BC8b <- vst_PCAdata %>% 
  filter(Genotype == "BC-8b")

# SI-C 
ggplot(vst_PCA_SIC, aes(PC1, PC2, color=Treatment, shape=time_point)) + 
   geom_point(size=3) +
   xlab(paste0("PC1: ",percentVar[1],"% variance")) +
   ylab(paste0("PC2: ",percentVar[2],"% variance")) +
   ggtitle("Acer genotype SI-C") +
   theme_bw() + 
   scale_color_manual(values = c("#00CCCC", "#FF3333"))

ggplot(vst_PCA_SIC, aes(PC1, PC2, color=group)) + 
   geom_point(size=3) +
   xlab(paste0("PC1: ",percentVar[1],"% variance")) +
   ylab(paste0("PC2: ",percentVar[2],"% variance")) +
   ggtitle("Acer genotype SI-C") +
   theme_bw() + 
  scale_color_manual(values = c("lightblue", "darkblue", "red", "darkred")) + 
  stat_ellipse(aes(PC1, PC2, group= group), type = "norm") 
  
# MB-B
ggplot(vst_PCA_MBB, aes(PC1, PC2, color=Treatment, shape=time_point)) + 
   geom_point(size=3) +
   xlab(paste0("PC1: ",percentVar[1],"% variance")) +
   ylab(paste0("PC2: ",percentVar[2],"% variance")) +
   ggtitle("Acer genotype MB-B") +
   theme_bw() + 
   scale_color_manual(values = c("#00CCCC", "#FF3333"))

ggplot(vst_PCA_MBB, aes(PC1, PC2, color=group)) + 
   geom_point(size=3) +
   xlab(paste0("PC1: ",percentVar[1],"% variance")) +
   ylab(paste0("PC2: ",percentVar[2],"% variance")) +
   ggtitle("Acer genotype MB-B") +
   theme_bw() + 
  scale_color_manual(values = c("lightblue", "darkblue", "red", "darkred")) + 
  stat_ellipse(aes(PC1, PC2, group= group), type = "norm") 


# BC-8b
ggplot(vst_PCA_BC8b, aes(PC1, PC2, color=Treatment, shape=time_point)) + 
   geom_point(size=3) +
   xlab(paste0("PC1: ",percentVar[1],"% variance")) +
   ylab(paste0("PC2: ",percentVar[2],"% variance")) +
   ggtitle("Acer genotype BC-8b") +
   theme_bw() + 
   scale_color_manual(values = c("#00CCCC", "#FF3333"))

  ggplot(vst_PCA_BC8b, aes(PC1, PC2, color=group)) + 
   geom_point(size=3) +
   xlab(paste0("PC1: ",percentVar[1],"% variance")) +
   ylab(paste0("PC2: ",percentVar[2],"% variance")) +
   ggtitle("Acer genotype Bc=8b") +
   theme_bw() + 
  scale_color_manual(values = c("lightblue", "darkblue", "red", "darkred")) + 
  stat_ellipse(aes(PC1, PC2, group= group), type = "norm") 

```

# PC axes 2 and 3
```{r}
## functions for PCA axes 2 and 3
#PCA 2 and 3 axis creation
pcaaxes23 = function (object, intgroup = "condition", ntop = 500, returnData = FALSE) 
{
    rv <- rowVars(assay(object))
    select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, 
        length(rv)))]
    pca <- prcomp(t(assay(object)[select, ]))
    percentVar <- pca$sdev^2/sum(pca$sdev^2)
    if (!all(intgroup %in% names(colData(object)))) {
        stop("the argument 'intgroup' should specify columns of colData(dds)")
    }
    intgroup.df <- as.data.frame(colData(object)[, intgroup, 
        drop = FALSE])
    group <- if (length(intgroup) > 1) {
        factor(apply(intgroup.df, 1, paste, collapse = ":"))
    }
    else {
        colData(object)[[intgroup]]
    }
    d <- data.frame(PC2 = pca$x[, 2], PC3 = pca$x[, 3], group = group, 
        intgroup.df, name = colnames(object))
    if (returnData) {
        attr(d, "percentVar") <- percentVar[2:3]
        return(d)
    }
    ggplot(data = d, aes_string(x = "PC2", y = "PC3", color = "group")) + 
        geom_point(size = 3) + xlab(paste0("PC2: ", round(percentVar[2] * 
        100), "% variance")) + ylab(paste0("PC3: ", round(percentVar[3] * 
        100), "% variance")) + coord_fixed()
}
```


```{r}
pca23 <- pcaaxes23(Vsd, intgroup=c("Treatment", "Genotype", "time_point"), returnData = TRUE)

pcaaxes23(Vsd, intgroup=c("Genotype"), returnData = F)

pcaaxes23(Vsd, intgroup=c("time_point"), returnData = F) #clearer separation of time point

pcaaxes23(Vsd, intgroup=c("Treatment"), returnData = F)

percentVar_pc23 <- round(100*attr(pca23, "percentVar")) 

ggplot(pca23, aes(PC2, PC3, color=Treatment, shape = time_point)) + 
   geom_point(size=3) +
   xlab(paste0("PC2: ",percentVar_pc23[1],"% variance")) +
   ylab(paste0("PC3: ",percentVar_pc23[2],"% variance")) +
   ggtitle("A. cervicornis") +
   theme_bw() + 
   stat_ellipse(aes(PC2, PC3, group=time_point, lty=time_point), type = "norm") +
   #facet_wrap(~time_point) +
   scale_color_manual(values = c("#00CCCC", "#FF3333"))

```



