---
title: "stresshardening2022"
author: "Allyson DeMerlis"
date: "4/4/2022"
output: html_document
---

```{r}
library(tidyverse)
library(plotrix) #for standard error function

feb4<- readxl::read_xlsx("Data from LabVIEW/20220204_TemperatureData edited.xlsx", col_types = c("date", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric"))
feb23 <- readxl::read_xlsx("Data from LabVIEW/20220223_TemperatureData edited.xlsx")
march7 <- readxl::read_xlsx("Data from LabVIEW/20220307_TemperatureData - Copy.xlsx")
march29 <- readxl::read_xlsx("Data from LabVIEW/20220329_TemperatureData.xlsx")
april15 <- readxl::read_xlsx("Data from LabVIEW/20220415_TemperatureData.xlsx")

april25 <- readxl::read_xlsx("Data from LabVIEW/20220425_TemperatureData (1).xlsx") #had to convert to csv because dates weren't reading in correctly

CBASS <- readxl::read_xlsx("Data from LabVIEW/CBASS_labview.xlsx")

may11 <- readxl::read_xlsx("Data from LabVIEW/20220511_TemperatureData.xlsx")
may20 <- readxl::read_xlsx("Data from LabVIEW/20220520_TemperatureData.xlsx")
june10 <- readxl::read_xlsx("Data from LabVIEW/20220610_TemperatureData - Copy.xlsx")
june24 <- readxl::read_xlsx("Data from LabVIEW/20220624_TemperatureData (1).xlsx")
july6 <- readxl::read_xlsx("Data from LabVIEW/20220706_TemperatureData.xlsx", 
    col_types = c("date", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric"))
july8 <- readxl::read_xlsx("Data from LabVIEW/20220708_TemperatureData edited.xlsx")
july20 <- read_csv("Data from LabVIEW/20220720_TemperatureData.csv") #had to convert to csv because dates weren't reading in correctly
  july20$Time <- lubridate::mdy_hms(july20$Time)
```

Creating subsets for different stages of experiment
```{r}
acclimation <- bind_rows(feb4, feb23) 
temptreatment<- bind_rows(march7, march29, april15) #treatment started march 24 and ended april 20
  temptreatment %>% filter(Time >= as.Date("2022-03-24") & Time <= as.Date("2022-04-22")) -> temptreatment
CBASS #april 22
recovery <- bind_rows(april15, april25, may11, may20, june10) #recovery started april 23 and ended june 21
  recovery %>% filter(Time >= as.Date("2022-04-23") & Time <= as.Date("2022-06-22")) -> recovery
heatstressassay <- bind_rows(june10, june24, july6, july8, july20) #ramp up started june 21
```


```{r}
#tanks 1-4 had Pclivosa in them since Feb 4, so they were maintained at 24 C. Tanks 5-8 didn't get Acer until Feb 24, so that's why their temps fluctuate before then.
#need to remove tank temps for tanks 5-8 for dates before feb 24 and before feb 17 for tanks 1-4
#ended up doing this manually in Excel

acclimation %>% 
  filter(Time >= as.Date("2022-02-17")) %>% 
  dplyr::select(Time:T8) %>% 
  pivot_longer(T1:T8, names_to="Tank", values_to ="Temp") %>% 
  ggplot(data = .,
       aes(x = Time, y = Temp, color = Tank)) +
  geom_line() + 
  theme_classic() +
  labs(title = "Tank Temperatures",
       y = "Temperature (°C)",
       x = "Date") +
  scale_y_continuous(limits = c(22, 26)) +
  theme(text = element_text(size = 16)) #all font sizes
```


```{r}
#need to clean up this graph,summarize all the tanks together
acclimation$Time <- lubridate::round_date(acclimation$Time, unit = "15 min")

acclimation %>% 
  filter(Time >= as.Date("2022-02-17")) %>% 
  dplyr::select(Time:T8) %>% 
  pivot_longer(T1:T8, names_to="Tank", values_to ="Temp") %>% 
  drop_na(Temp) %>% 
  dplyr::group_by(Time) %>% 
  dplyr::summarise(avg_temp = mean(Temp), se = std.error(Temp)) %>% 
  ggplot(., aes(x=Time, y=avg_temp)) + 
  geom_point() +
  geom_smooth() +
  theme_classic() +
   geom_line() +
  labs(title = "Tank Temperatures",
       y = "Temperature (°C)",
       x = "Date") +
  scale_y_continuous(limits = c(22, 26)) +
  theme(text = element_text(size = 16)) #all font sizes
```

```{r}
#all tanks separated
temptreatment %>% 
  dplyr::select(Time:T8) %>% 
  pivot_longer(T1:T8, names_to="Tank", values_to ="Temp") %>% 
  ggplot(data = .,
       aes(x = Time, y = Temp, color = Tank)) +
  geom_point() + 
  theme_classic() +
  facet_wrap(~Tank) +
  labs(title = "Tank Temperatures",
       y = "Temperature (°C)",
       x = "Date")
```

```{r}
#summary figure of average tank temp during 24-hr period over the 28 days
temptreatment$Time <- lubridate::round_date(temptreatment$Time, unit = "15 min")

temptreatment %>% 
  filter(Time >= "2022-03-24 09:00:00") %>% 
  filter(Time <= "2022-04-20 09:00:00") %>% 
    #remove tissue sampling time points because during those times, you modified the tank temps to all hold at  28 C
  filter(!Time >= "2022-03-30 09:00:00" | !Time <= "2022-03-31 09:00:00") %>% 
  dplyr::select(Time:T8) %>% 
  pivot_longer(T1:T8, names_to="Tank", values_to ="Temp") %>% 
  tidyr::separate(Time, c("Date", "Time"), sep = "\\ ") %>% 
  mutate(treatment = case_when(Tank == "T1" ~ "control",
                               Tank == "T2" ~ "variable",
                               Tank == "T3" ~ "variable",
                               Tank == "T4" ~ "control",
                               Tank == "T5" ~ "variable", 
                               Tank == "T6" ~ "control",
                               Tank == "T7" ~ "control",
                               Tank == "T8" ~ "variable")) %>% 
  dplyr::group_by(Time, treatment) %>% 
  dplyr::summarise(avg_temp = mean(Temp), sd = sd(Temp)) %>% 
  ggplot(., aes(x=Time, y=avg_temp, color = treatment)) + 
  theme_classic() +
  geom_ribbon(aes(fill=treatment, group = treatment, ymin = avg_temp - sd, ymax = avg_temp + sd), alpha = 0.2) +
   geom_line(aes(group = treatment)) +
  scale_x_discrete(breaks = c("03:00:00", "09:00:00", "15:00:00", "21:00:00")) +
  labs(y="Temperature (C)") +
  scale_color_manual(labels=c("Control", "Variable"), values = c( "#60DBDB", "#F54A34"))+
  scale_fill_manual(labels=c("Control", "Variable"), values = c( "#60DBDB", "#F54A34")) +
  theme(text = element_text(size = 15)) 
```

```{r}
#with standard error instead of standard deviation

temptreatment %>% 
  filter(Time >= "2022-03-24 09:00:00") %>% 
  filter(Time <= "2022-04-20 09:00:00") %>% 
    #remove tissue sampling time points because during those times, you modified the tank temps to all hold at  28 C
  filter(!Time >= "2022-03-30 09:00:00" | !Time <= "2022-03-31 09:00:00") %>% 
  dplyr::select(Time:T8) %>% 
  pivot_longer(T1:T8, names_to="Tank", values_to ="Temp") %>% 
  tidyr::separate(Time, c("Date", "Time"), sep = "\\ ") %>% 
  mutate(treatment = case_when(Tank == "T1" ~ "control",
                               Tank == "T2" ~ "variable",
                               Tank == "T3" ~ "variable",
                               Tank == "T4" ~ "control",
                               Tank == "T5" ~ "variable", 
                               Tank == "T6" ~ "control",
                               Tank == "T7" ~ "control",
                               Tank == "T8" ~ "variable")) %>% 
  dplyr::group_by(Time, treatment) %>% 
  dplyr::summarise(avg_temp = mean(Temp), se = std.error(Temp)) %>% 
  ggplot(., aes(x=Time, y=avg_temp, color = treatment)) + 
  theme_classic() +
  geom_ribbon(aes(fill=treatment, group = treatment, ymin = avg_temp - se, ymax = avg_temp + se), alpha = 0.2) +
   geom_line(aes(group = treatment)) +
  scale_x_discrete(breaks = c("03:00:00", "09:00:00", "15:00:00", "21:00:00")) +
  labs(y="Temperature (C)") +
  scale_color_manual(labels=c("Control", "Variable"), values = c( "#60DBDB", "#F54A34"))+
  scale_fill_manual(labels=c("Control", "Variable"), values = c( "#60DBDB", "#F54A34")) +
  theme(text = element_text(size = 15)) 
```


```{r}
CBASS %>% 
  dplyr::select(Time:`8`) %>% 
  pivot_longer(`1`:`8`, names_to="Tank", values_to ="Temp") %>% 
  ggplot(data = .,
       aes(x = Time, y = Temp, color = Tank)) +
  geom_point() + 
  theme_classic() +
  facet_wrap(~Tank) +
  labs(title = "Tank Temperatures",
       y = "Temperature (°C)",
       x = "Date")
```

```{r}
CBASS %>% 
  dplyr::select(Time:`8`) %>% 
  pivot_longer(`1`:`8`, names_to="Tank", values_to ="Temp") %>% 
  ggplot(data = .,
       aes(x = Time, y = Temp, color = Tank)) +
  geom_line() + 
  theme_classic() +
  labs(title = "Tank Temperatures",
       y = "Temperature (°C)",
       x = "Hour") +
  theme(text = element_text(size = 15)) 
```


```{r}
recovery %>% 
  dplyr::select(Time:T8) %>% 
  pivot_longer(T1:T8, names_to="Tank", values_to ="Temp") %>% 
  ggplot(data = .,
       aes(x = Time, y = Temp, color = Tank)) +
  geom_point() + 
  theme_classic() +
  facet_wrap(~Tank) +
  labs(title = "Tank Temperatures",
       y = "Temperature (°C)",
       x = "Date")

#not all of these tanks were used for recovery, check metadata sheet to confirm which tanks we got rid of
```


```{r}
recovery %>% 
  dplyr::select(Time, T3, T4, T6, T7, T8) %>% 
  pivot_longer(T3:T8, names_to="Tank", values_to ="Temp") %>% 
  ggplot(data = .,
       aes(x = Time, y = Temp, color = Tank)) +
  geom_line() + 
  theme_classic() +
  labs(title = "Tank Temperatures",
       y = "Temperature (°C)",
       x = "Date") +
  theme(text = element_text(size = 15)) 
```


```{r}
#need to clean up this graph,summarize all the tanks together
recovery$Time <- lubridate::round_date(recovery$Time, unit = "15 min")

recovery %>% 
  dplyr::filter(Time <= as.Date("2022-06-21")) %>% 
  dplyr::select(Time, T3, T4, T6, T7, T8)  %>% 
  dplyr::select(Time:T8) %>% 
  pivot_longer(T3:T8, names_to="Tank", values_to ="Temp") %>% 
  drop_na(Temp) %>% 
  dplyr::group_by(Time) %>% 
  dplyr::summarise(avg_temp = mean(Temp), se = std.error(Temp)) %>% 
  ggplot(., aes(x=Time, y=avg_temp)) + 
  geom_point() +
  geom_smooth() +
  theme_classic() +
  labs(title = "Tank Temperatures",
       y = "Temperature (°C)",
       x = "Date") +
  scale_y_continuous(limits = c(27, 29)) +
  theme(text = element_text(size = 16)) #all font sizes
```


```{r}
heatstressassay %>% 
  dplyr::select(Time:T8) %>% 
  pivot_longer(T1:T8, names_to="Tank", values_to ="Temp") %>% 
  ggplot(data = .,
       aes(x = Time, y = Temp, color = Tank)) +
  geom_point() + 
  theme_classic() +
  facet_wrap(~Tank) +
  labs(title = "Tank Temperatures",
       y = "Temperature (°C)",
       x = "Date")

#was it just tanks 3, 4, and 8 that we used as the heat stress assay tanks? What was happening in tank 1?
```

```{r}
heatstressassay %>% 
  dplyr::select(Time, T3, T4, T7, T8) %>% 
  pivot_longer(T3:T8, names_to="Tank", values_to ="Temp") %>% 
  ggplot(data = .,
       aes(x = Time, y = Temp, color = Tank)) +
  geom_line() + 
  theme_classic() +
  labs(title = "Tank Temperatures",
       y = "Temperature (°C)",
       x = "Date") +
  theme(text = element_text(size = 15)) 

#this is messy because each tank was "stopped" at different times, depending on when all the corals died or not. there was a dip in temps for all of them where they went back down to 28 because of human error in setting the program

#need to manually edit the Excel sheet to remove the time points once the heat-stress was completed for each tank
```


```{r}
heatstressassay$Time <- lubridate::round_date(heatstressassay$Time, unit = "15 min")

heatstressassay %>% 
  dplyr::select(Time, T3, T4, T8) %>% 
  dplyr::select(Time:T8) %>% 
  pivot_longer(T3:T8, names_to="Tank", values_to ="Temp") %>% 
  drop_na(Temp) %>% 
  dplyr::group_by(Time) %>% 
  dplyr::summarise(avg_temp = mean(Temp), se = std.error(Temp)) %>% 
  ggplot(., aes(x=Time, y=avg_temp)) + 
  geom_point() +
  geom_smooth() +
  theme_classic() +
  labs(title = "Tank Temperatures",
       y = "Temperature (°C)",
       x = "Date") +
  #scale_y_continuous(limits = c(27, 29)) +
  theme(text = element_text(size = 16)) #all font sizes
```

