---
title: "coralmortality"
author: "allyson_demerlis"
date: "2023-02-20"
output: html_document
---

```{r}
metadata <- readxl::read_xlsx("../metadata.xlsx")

library(tidyverse)
library(janitor)
library(rstatix)
```



```{r}
metadata %>% 
  dplyr::select(Species:Colony, Treatment, Removed_Date, Reason_removed, mortality_date, Notes) -> mortality_data

#fix excel dates
#columns must be numeric
mortality_data$Removed_Date <- as.numeric(mortality_data$Removed_Date)
mortality_data$mortality_date <- as.numeric(mortality_data$mortality_date)

mortality_data$Removed_Date <- excel_numeric_to_date(mortality_data$Removed_Date)
mortality_data$mortality_date <- excel_numeric_to_date(mortality_data$mortality_date)
```


```{r}
mortality_data %>% 
  dplyr::filter(Removed_Date >= "2022-04-20" & Removed_Date <= "2022-04-25") %>% 
  drop_na(Species, Treatment, Reason_removed) %>% 
  group_by(Reason_removed, Species, Treatment) %>% 
  summarize(count = n()) %>% 
  ggplot(., aes(x=Reason_removed, y=count, fill = Treatment)) +
  geom_col(position = position_dodge()) +
  theme_classic() +
  facet_wrap(~Species, scales = "free")  +
  scale_fill_manual(labels=c("Control", "Variable"), values = c( "#60DBDB", "#F54A34"))  +
  theme(text = element_text(size = 15)) +
  labs(x="Category", y="Number of corals") + 
  coord_flip()
```

```{r}
#mortality just on the day of the CBASS

mortality_data %>% 
  dplyr::filter(Removed_Date == "2022-04-22" | mortality_date == "2022-04-22") %>% 
  drop_na(Species, Treatment, Reason_removed) %>% 
  group_by(Reason_removed, Species, Treatment) %>% 
  summarize(count = n()) %>% 
  ggplot(., aes(x=Reason_removed, y=count, fill = Treatment)) +
  geom_col(position = position_dodge()) +
  theme_classic() +
  facet_wrap(~Species, scales = "free")  +
  scale_fill_manual(labels=c("Control", "Variable"), values = c( "#60DBDB", "#F54A34"))  +
  theme(text = element_text(size = 15)) +
  labs(x="Category", y="Number of corals") + 
  coord_flip()
```

```{r}
#total nunmber of corals per species
mortality_data %>% 
  dplyr::filter(Removed_Date >= "2022-04-21" & Removed_Date <= "2022-04-25") %>% 
  mutate(Reason_removed = case_when(Reason_removed == "dead" ~ "RTL",
                             Reason_removed == "post-CBASS RTL" ~ "RTL",
                             Reason_removed == "RTL" ~ "RTL")) %>% 
  drop_na(Species, Treatment, Reason_removed) %>% 
  group_by(Reason_removed, Species, Treatment) %>% 
  summarize(count = n()) %>% 
  ggplot(., aes(x=Species, y=count, fill = Treatment)) +
  geom_col(position = position_dodge()) +
  theme_classic() +
  scale_fill_manual(labels=c("Control", "Variable"), values = c( "#60DBDB", "#F54A34"))  +
  theme(text = element_text(size = 15)) +
  labs(y="Number of corals", title = "Mortality post-CBASS due to RTL")
```


```{r}
#proportion of corals that died during/post-CBASS versus the total number of corals that went into the CBASS
mortality_data %>% 
  dplyr::filter(Removed_Date >= "2022-04-21" & Removed_Date <= "2022-04-25") %>% 
  mutate(Reason_removed = case_when(Reason_removed == "dead" ~ "RTL",
                             Reason_removed == "post-CBASS RTL" ~ "RTL",
                             Reason_removed == "RTL" ~ "RTL")) %>% 
  drop_na(Species, Treatment) %>% 
  group_by(Species, Treatment) %>% 
  summarize(count_RTL = n()) -> RTL_species_treatment_count

mortality_data %>% 
  dplyr::filter(!Removed_Date <= "2022-04-20" | is.na(Removed_Date)) %>% #remove everything that was removed before CBASS so you only account for RTL due to CBASS
  group_by(Species, Treatment) %>% 
  summarize(count_total = n()) %>% 
  full_join(., RTL_species_treatment_count) %>% 
  mutate(proportion_RTL = (count_RTL/count_total)*100) %>% #need total number of corals that were alive at that time
  ggplot(., aes(x=Species, y=proportion_RTL, fill = Treatment)) +
  geom_col(position = position_dodge()) +
  theme_classic() +
  scale_fill_manual(labels=c("Control", "Variable"), values = c( "#60DBDB", "#F54A34"))  +
  theme(text = element_text(size = 15)) +
  labs(y="% Mortality due to RTL")  + 
  coord_flip() +
  theme(text = element_text(size = 20)) 
ggsave("coralmortalityduetoCBASS.png", width = 10, height =6)
```


```{r}
#chi squared test for comparing mortality numbers
mortality_data %>% 
  dplyr::filter(!Removed_Date <= "2022-04-20" | is.na(Removed_Date)) %>% 
  group_by(Species, Treatment) %>% 
  summarize(count_total = n()) %>% 
  full_join(., RTL_species_treatment_count) %>% 
  mutate(count_survived = count_total - count_RTL) %>% 
  filter(Species == "Acropora cervicornis") %>% 
  ungroup() %>% 
  dplyr::select(Treatment, count_RTL, count_survived) %>% 
  mutate(Treatment = as.factor(Treatment)) %>% 
  column_to_rownames(var = "Treatment")-> Acer_contingencytable

chisq_test(Acer_contingencytable)

goodnessOfFitTest(Acer_contingencytable)

mortality_data %>% 
  dplyr::filter(Removed_Date >= "2022-04-21" & Removed_Date <= "2022-04-25") %>% 
  mutate(Reason_removed = case_when(Reason_removed == "dead" ~ "RTL",
                             Reason_removed == "post-CBASS RTL" ~ "RTL",
                             Reason_removed == "RTL" ~ "RTL")) %>% 
  drop_na(Species, Treatment, Reason_removed) %>% 
  select(Species, Treatment, Reason_removed)
```