---
title: "fvfm_prepostCBASS"
author: "allyson_demerlis"
date: "2024-01-02"
output: html_document
---

# Packages

```{r}
library(tidyverse)
library(plotrix)
library(lme4)
library(ggpubr)
library(drc) #for the function "drm" dose-response model
library(broom) #for the tidy function needed for dose response model
library(car)
library(rstatix)
library(rcompanion)
library(cowplot)
library(dunn.test)
```

# Import and tidy data

```{r}
ipam_tidy_data <- read.csv("ipam_tidy_data.csv")

ipam_tidy_data %>% 
  dplyr::filter(Treatment_period == "CBASS") %>% 
  dplyr::select(!Treatment) -> ipam_tidy_CBASS

ipam_tidy_data %>% 
  dplyr::filter(!Treatment_period == "CBASS") %>% 
  dplyr::select(Tank, Puck, Colony, Treatment, Species) %>% 
  distinct() %>% #283 rows = one coral ID per treatment, no repeats
  mutate(Treatment = case_when(Tank == "1" ~ "Untreated",
                               Tank == "2" ~ "Treated",
                               Tank == "3" ~ "Treated",
                               Tank == "4" ~ "Untreated",
                               Tank == "5" ~ "Treated", 
                               Tank == "6" ~ "Untreated",
                               Tank == "7" ~ "Untreated",
                               Tank == "8" ~ "Treated")) %>% 
  full_join(ipam_tidy_CBASS, by = c("Puck", "Colony", "Species")) %>% 
  drop_na() %>% 
  rename(Treatment_Tank = Tank.x, CBASS_Tank = Tank.y) %>% 
  dplyr::select(-c("X", "AOI", "Ft", "Fm", "file", "Treatment_period", "CBASS_Tank")) -> ipam_tidy_CBASS_treatments

ipam_tidy_CBASS_treatments %>% 
  mutate_at(vars(Colony, Puck, Treatment, Species), factor) -> ipam_tidy_CBASS_treatments
```


create pre-CBASS and post-CBASS data frame (fvfm measured on April 20, last day of treatment, and April 22 for CBASS)
```{r}
ipam_tidy_CBASS %>% 
  select(Puck, Colony, Species, CBASS_temp) -> CBASS_temp_metadata

ipam_tidy_data %>% 
  filter(Date == "2022-04-20") %>% 
  select(fvfm, Tank, Puck, Colony, Date, Treatment, Species) %>% 
    mutate(Treatment = case_when(Tank == "1" ~ "Untreated",
                               Tank == "2" ~ "Treated",
                               Tank == "3" ~ "Treated",
                               Tank == "4" ~ "Untreated",
                               Tank == "5" ~ "Treated", 
                               Tank == "6" ~ "Untreated",
                               Tank == "7" ~ "Untreated",
                               Tank == "8" ~ "Treated")) %>% 
  rename(Treatment_Tank = Tank) %>% 
  inner_join(CBASS_temp_metadata) %>% 
  rbind(ipam_tidy_CBASS_treatments) %>% 
  pivot_wider(names_from = "Date", values_from = "fvfm") %>% 
  mutate(fvfm_loss_norm = (`2022-04-20` - `2022-04-22`)/`2022-04-20`) -> prepostCBASS
```


```{r}
prepostCBASS %>% 
  mutate(CBASS_temp = as.factor(CBASS_temp)) %>% 
  ggplot(., aes(x=CBASS_temp, y= fvfm_loss_norm, fill = Treatment)) + 
  geom_boxplot() +
  facet_wrap(~Species) + 
  theme_classic() +
  labs(y = "% Decline in Fv/Fm", x="Treatment") +
  scale_fill_manual(labels=c("Treated", "Untreated"), values = c("#F54A34", "#60DBDB")) +
  theme(text = element_text(size = 15)) 
```

