---
title: "heatstress_PCLIV_April2023"
author: "Lys Isma"
date: "5/3/2023"
output: pdf_document
---

```{r}
#PCLIV
#average percentage per SPECIES
library(tidyverse)
library(dplyr)
library(Rmisc)

# read in raw data from FlowJo
pcliv= read.csv("~/Downloads/pcliv_metadata.csv")

head(pcliv)
str(pcliv)

# clean up names of columns and make treatments of interest factors
pcliv_clean = pcliv %>%
  mutate(Temperature = as.factor(Temperature),
         Genotype = as.factor(Genotype), Replicate = as.factor(Replicate), Treatment = as.factor(Treatment)) %>%
  dplyr::rename(Num_Cells = Num_Cells) %>%
  dplyr::rename(Avg_Control = Average_Control) %>%
  dplyr::rename(Adj_Percent = Adjusted_Value_T)

str(pcliv_clean)

# subset data to only look at bead and Ecoli treatments, since data has been corrected to controls
pcliv_treatments = pcliv_clean %>%
  subset(Treatment == "beads" | Treatment == "ecoli"| Treatment == "dextrane")

# calculate mean percent of cells across the three replicate measurements
pcliv_summary = pcliv_treatments %>%
  #group_by(Genotype, Temperature, Treatment) %>%
  #dplyr::summarize(mean_percent = mean(Adj_Percent)) %>%
  unite(temp_treat, c(Temperature,Treatment), sep = "_", remove = FALSE) %>%
  mutate(temp_treat = as.factor(temp_treat)) %>%
  droplevels()


# PLOT phagocytes

# use summarySE to group data for plotting
cell_means <- summarySE(pcliv_summary, measurevar="Adj_Percent", groupvars=c("Temperature","Treatment"))

# plot, temperature  x axis colored by beads/ecoli treatment
plot <- ggplot(pcliv_summary, aes(x = Temperature, y = Adj_Percent))+
  theme_bw()+
  geom_jitter(aes(color = Treatment, fill = Treatment),
              position=position_dodge(width=0.3),
              alpha=0.2, pch = 21,
              color = "black") +
  geom_errorbar(data = cell_means, aes(x = Temperature, ymax = Adj_Percent+se, ymin = Adj_Percent-se, color = Treatment), width = .2, position = position_dodge(width=0.4)) +
  #scale_color_manual(values = c("#ca7dcc","#006600",
                             #   "#1b98e0"))+
  geom_point(data = cell_means, mapping = aes(x=Temperature, y=Adj_Percent, color = lineage, fill = Treatment), size = 3.5, pch = 21, color = "black", position = position_dodge(width=0.4))+
  #scale_fill_manual(values = c("#ca7dcc","#006600",
                               # "#1b98e0"))+
  #scale_fill_manual(name = "Treatment",
  #                  breaks = c("L1","L2"),
  #                  values = cols_lineage)+
  #scale_color_manual(name = "Lineage",
  #                   breaks = c("L1","L2"),
  #                   values = cols_lineage)+
  ggtitle("P.CLIV")+
  xlab("Temperature")+
  ylab("Adjusted Percent of Phagocytes")+
  theme(panel.border = element_rect(colour = "black", fill = NA, size = 1)) 
plot
#save plot
ggsave(plot, filename = "OverallAveragePcliv.pdf", width=6, height=4, units=c("in"), useDingbats=FALSE)

```
```{r}
#PCLIV
#average percentage per genotype
library(tidyverse)
library(dplyr)
library(Rmisc)

# read in raw data from FlowJo
pcliv= read.csv("/Users/lysis/Downloads/pcliv_metadata.csv")

head(pcliv)
str(pcliv)

# clean up names of columns and make treatments of interest factors
pcliv_clean = pcliv %>%
  mutate(Temperature = as.factor(Temperature), ,
         Genotype = as.factor(Genotype), Replicate = as.factor(Replicate), Treatment = as.factor(Treatment)) %>%
  dplyr::rename(Num_Cells = Num_Cells) %>%
  dplyr::rename(Avg_Control = Average_Control) %>%
  dplyr::rename(Adj_Percent = Adjusted_Value_T)

str(pcliv_clean)

# subset data to only look at bead and Ecoli treatments, since data has been corrected to controls
pcliv_treatments = pcliv_clean %>%
  subset(Treatment == "beads")

# calculate mean percent of cells across the three replicate measurements
pcliv_summary = pcliv_treatments %>%
  #group_by(Genotype, Temperature, Treatment) %>%
  #dplyr::summarize(mean_percent = mean(Adj_Percent)) %>%
  unite(temp_treat, c(Temperature,Treatment), sep = "_", remove = FALSE) %>%
  mutate(temp_treat = as.factor(temp_treat)) %>%
  droplevels()


# PLOT phagocytes

# use summarySE to group data for plotting
cell_means <- summarySE(pcliv_summary, measurevar="Adj_Percent", groupvars=c("Temperature","Treatment","Genotype"))

# plot, temperature  x axis colored by beads/ecoli treatment
plot <- ggplot(pcliv_summary, aes(x = Temperature, y = Adj_Percent))+
  theme_bw()+
  geom_jitter(aes(color = Treatment, fill = Treatment),
              position=position_dodge(width=0.3),
              alpha=0.2, pch = 21,
              color = "black") +
  geom_errorbar(data = cell_means, aes(x = Temperature, ymax = Adj_Percent+se, ymin = Adj_Percent-se, color = Treatment), width = .2, position = position_dodge(width=0.4)) +#scale_color_manual(values = c("#ca7dcc",
                                #"#1b98e0"))+
  geom_point(data = cell_means, mapping = aes(x=Temperature, y=Adj_Percent, color = lineage, fill = Treatment), size = 3.5, pch = 21, color = "black", position = position_dodge(width=0.4))+
   #scale_fill_manual(values = c("#ca7dcc",
                               # "#1b98e0"))+
  #scale_fill_manual(name = "Treatment",
  #                  breaks = c("L1","L2"),
  #                  values = cols_lineage)+
  #scale_color_manual(name = "Lineage",
  #                   breaks = c("L1","L2"),
  #                   values = cols_lineage)+
  ggtitle("P.CLIV")+
  xlab("Temperature")+
  ylab("Adjusted Percent of Phagocytes")+
  theme(panel.border = element_rect(colour = "black", fill = NA, size = 1)) +
  facet_wrap(~Genotype, nrow = 2, ncol = 4)
plot
#save plot
ggsave(plot, filename = "GENOTYPE_pcliv_meanpercentphagocytes.pdf", width=6, height=4, units=c("in"), useDingbats=FALSE)

```

```{r}

```




```{r}
#PCLIV
#average percentage per SPECIES just beads
library(tidyverse)
library(dplyr)
library(Rmisc)

# read in raw data from FlowJo
pcliv= read.csv("/Users/lysis/Downloads/pcliv_metadata.csv")

head(pcliv)
str(pcliv)

# clean up names of columns and make treatments of interest factors
pcliv_clean = pcliv %>%
  mutate(Temperature = as.factor(Temperature), ,
         Genotype = as.factor(Genotype), Replicate = as.factor(Replicate), Treatment = as.factor(Treatment)) %>%
  dplyr::rename(Num_Cells = Num_Cells) %>%
  dplyr::rename(Avg_Control = Average_Control) %>%
  dplyr::rename(Adj_Percent = Adjusted_Value_T)

str(pcliv_clean)

# subset data to only look at bead and Ecoli treatments, since data has been corrected to controls
pcliv_treatments = pcliv_clean %>%
  subset(Treatment == "beads")

# calculate mean percent of cells across the three replicate measurements
pcliv_summary = pcliv_treatments %>%
  #group_by(Genotype, Temperature, Treatment) %>%
  #dplyr::summarize(mean_percent = mean(Adj_Percent)) %>%
  unite(temp_treat, c(Temperature,Treatment), sep = "_", remove = FALSE) %>%
  mutate(temp_treat = as.factor(temp_treat)) %>%
  droplevels()


# PLOT phagocytes

# use summarySE to group data for plotting
cell_means <- summarySE(pcliv_summary, measurevar="Adj_Percent", groupvars=c("Temperature","Treatment"))

# plot, temperature  x axis colored by beads/ecoli treatment
plot <- ggplot(pcliv_summary, aes(x = Temperature, y = Adj_Percent))+
  theme_bw()+
  geom_jitter(aes(color = Treatment, fill = Treatment),
              position=position_dodge(width=0.3),
              alpha=0.2, pch = 21,
              color = "black") +
  geom_errorbar(data = cell_means, aes(x = Temperature, ymax = Adj_Percent+se, ymin = Adj_Percent-se, color = Treatment), width = .2, position = position_dodge(width=0.4)) +
   geom_signif(data = pcliv_beads,
    comparisons= list(c("24", "28"),
                      c("24", "32"), 
                      c("36", "24")),
  step_increase = 0.3,
  #test = "TukeyHSD",
   map_signif_level = c("***"=0.001, "**"=0.01, "*"=0.05), 
    textsize = 3) +
  #scale_color_manual(values = c("#ca7dcc","#006600",
                             #   "#1b98e0"))+
  geom_point(data = cell_means, mapping = aes(x=Temperature, y=Adj_Percent, color = lineage, fill = Treatment), size = 3.5, pch = 21, color = "black", position = position_dodge(width=0.4))+
  #scale_fill_manual(values = c("#ca7dcc","#006600",
                               # "#1b98e0"))+
  #scale_fill_manual(name = "Treatment",
  #                  breaks = c("L1","L2"),
  #                  values = cols_lineage)+
  #scale_color_manual(name = "Lineage",
  #                   breaks = c("L1","L2"),
  #                   values = cols_lineage)+
  ggtitle("P.CLIV")+
  xlab("Temperature")+
  ylab("Adjusted Percent of Phagocytes")+
  theme(panel.border = element_rect(colour = "black", fill = NA, size = 1)) 
plot
#save plot
ggsave(plot, filename = "OverallAveragePcliv.pdf", width=6, height=4, units=c("in"), useDingbats=FALSE)
```


```{r}
#PCLIV
#relative per genotype
library(tidyverse)
library(dplyr)
library(Rmisc)

# read in raw data from FlowJo
pcliv= read.csv("/Users/lysis/Downloads/pcliv_metadata.csv")

head(pcliv)
str(pcliv)

# clean up names of columns and make treatments of interest factors
pcliv_clean = pcliv %>%
  mutate(Temperature = as.factor(Temperature), ,
         Genotype = as.factor(Genotype), Replicate = as.factor(Replicate), Treatment = as.factor(Treatment)) %>%
  dplyr::rename(Num_Cells = Num_Cells) %>%
  dplyr::rename(Avg_Control = Average_Control) %>%
  dplyr::rename(Adj_Percent_A = Adjusted_Value_A) %>%
  dplyr::rename(Adj_Percent = Adjusted_Value_T)

str(pcliv_clean)

# subset data to only look at bead and Ecoli treatments, since data has been corrected to controls
pcliv_treatments = pcliv_clean %>%
  subset(Treatment == "beads" | Treatment == "ecoli")

# calculate mean percent of cells across the three replicate measurements
pcliv_summary = pcliv_treatments %>%
  #group_by(Genotype, Temperature, Treatment) %>%
  #dplyr::summarize(mean_percent = mean(Adj_Percent)) %>%
  unite(temp_treat, c(Temperature,Treatment), sep = "_", remove = FALSE) %>%
  mutate(temp_treat = as.factor(temp_treat)) %>%
  droplevels()


# PLOT phagocytes

# use summarySE to group data for plotting
cell_means <- summarySE(pcliv_summary, measurevar="Adj_Percent_A", groupvars=c("Temperature","Treatment","Genotype"))

# plot, temperature  x axis colored by beads/ecoli treatment
plot <- ggplot(pcliv_summary, aes(x = Temperature, y = Adj_Percent_A))+
  theme_bw()+
  geom_jitter(aes(color = Treatment, fill = Treatment),
              position=position_dodge(width=0.3),
              alpha=0.2, pch = 21,
              color = "black") +
  geom_errorbar(data = cell_means, aes(x = Temperature, ymax = Adj_Percent_A+se, ymin = Adj_Percent_A-se, color = Treatment), width = .2, position = position_dodge(width=0.4)) +
  scale_color_manual(values = c("#ca7dcc",
                                "#1b98e0"))+
  geom_point(data = cell_means, mapping = aes(x=Temperature, y=Adj_Percent_A, color = lineage, fill = Treatment), size = 3.5, pch = 21, color = "black", position = position_dodge(width=0.4))+
  scale_fill_manual(values = c("#ca7dcc",
                                "#1b98e0"))+
  #scale_fill_manual(name = "Treatment",
  #                  breaks = c("L1","L2"),
  #                  values = cols_lineage)+
  #scale_color_manual(name = "Lineage",
  #                   breaks = c("L1","L2"),
  #                   values = cols_lineage)+
  xlab("Temperature")+
  ylab("Relative Activity")+
  theme(panel.border = element_rect(colour = "black", fill = NA, size = 1)) +
  facet_wrap(~Genotype, nrow = 2, ncol = 4)
plot
#save plot
ggsave(plot, filename = "RELATIVE_GENOTYPE_PCLIV.pdf", width=6, height=4, units=c("in"), useDingbats=FALSE)

```
```{r}
#PCLIV
#relative activity per SPECIES
library(tidyverse)
library(dplyr)
library(Rmisc)

# read in raw data from FlowJo
pcliv= read.csv("/Users/lysis/Downloads/pcliv_metadata.csv")

head(pcliv)
str(pcliv)

# clean up names of columns and make treatments of interest factors
pcliv_clean = pcliv %>%
  mutate(Temperature = as.factor(Temperature), ,
         Genotype = as.factor(Genotype), Replicate = as.factor(Replicate), Treatment = as.factor(Treatment)) %>%
  dplyr::rename(Num_Cells = Num_Cells) %>%
  dplyr::rename(Avg_Control = Average_Control) %>%
  dplyr::rename(Adj_Percent_A = Adjusted_Value_A) %>%
  dplyr::rename(Adj_Percent = Adjusted_Value_T)

str(pcliv_clean)

# subset data to only look at bead and Ecoli treatments, since data has been corrected to controls
pcliv_treatments = pcliv_clean %>%
  subset(Treatment == "beads")

# calculate mean percent of cells across the three replicate measurements
pcliv_summary = pcliv_treatments %>%
  #group_by(Genotype, Temperature, Treatment) %>%
  #dplyr::summarize(mean_percent = mean(Adj_Percent_A)) %>%
  unite(temp_treat, c(Temperature,Treatment), sep = "_", remove = FALSE) %>%
  mutate(temp_treat = as.factor(temp_treat)) %>%
  droplevels()


# PLOT phagocytes

# use summarySE to group data for plotting
cell_means <- summarySE(pcliv_summary, measurevar="Adj_Percent_A", groupvars=c("Temperature","Treatment"))

# plot, temperature  x axis colored by beads/ecoli treatment
plot <- ggplot(pcliv_summary, aes(x = Temperature, y = Adj_Percent_A))+
  theme_bw()+
  geom_jitter(aes(color = Treatment, fill = Treatment),
              position=position_dodge(width=0.3),
              alpha=0.2, pch = 21,
              color = "black") +
  geom_errorbar(data = cell_means, aes(x = Temperature, ymax = Adj_Percent_A+se, ymin = Adj_Percent_A-se, color = Treatment), width = .2, position = position_dodge(width=0.4)) +
  geom_signif(data = pcliv_summary,
    comparisons= list(c("24", "28"),
                      c("24", "32"), 
                      c("36", "24")),
  step_increase = 0.1,
  #test = "TukeyHSD",
   map_signif_level = c("***"=0.001, "**"=0.01, "*"=0.05), 
    textsize = 3) +
  #scale_color_manual(values = c("#ca7dcc",
                               # "#1b98e0"))+
  geom_point(data = cell_means, mapping = aes(x=Temperature, y=Adj_Percent_A, color = lineage, fill = Treatment), size = 3.5, pch = 21, color = "black", position = position_dodge(width=0.4))+
  #scale_fill_manual(values = c("#ca7dcc",
                               # "#1b98e0"))+
  #scale_fill_manual(name = "Treatment",
  #                  breaks = c("L1","L2"),
  #                  values = cols_lineage)+
  #scale_color_manual(name = "Lineage",
  #                   breaks = c("L1","L2"),
  #                   values = cols_lineage)+
  xlab("Temperature")+
  ggtitle("PCLIV_Relative_Activity")+
  ylab("Relative Activity")+
  theme(panel.border = element_rect(colour = "black", fill = NA, size = 1)) 
plot
#save plot
ggsave(plot, filename = "RELATIVE_pcliv.pdf", width=6, height=4, units=c("in"), useDingbats=FALSE)

```

```{r}
#PCLIV
#amount phagocytes activity per SPECIES with beads compared to dextrane
library(tidyverse)
library(dplyr)
library(Rmisc)

# read in raw data from FlowJo
pcliv= read.csv("/Users/lysis/Downloads/pcliv_metadata.csv")

head(pcliv)
str(pcliv)

# clean up names of columns and make treatments of interest factors
pcliv_clean = pcliv %>%
  mutate(Temperature = as.factor(Temperature), ,
         Genotype = as.factor(Genotype), Replicate = as.factor(Replicate), Treatment = as.factor(Treatment)) %>%
  dplyr::rename(Num_Cells = Num_Cells) %>%
  dplyr::rename(Avg_Control = Average_Control) %>%
  dplyr::rename(Adj_Percent_A = Adjusted_Value_A) %>%
  dplyr::rename(Adj_Percent = Adjusted_Value_T)

str(pcliv_clean)

# subset data to only look at bead and Ecoli treatments, since data has been corrected to controls
pcliv_treatments = pcliv_clean %>%
  subset(Treatment == "beads"| Treatment == "dextrane" )

# calculate mean percent of cells across the three replicate measurements
pcliv_summary = pcliv_treatments %>%
  #group_by(Genotype, Temperature, Treatment) %>%
  #dplyr::summarize(mean_percent = mean(Adj_Percent)) %>%
  unite(temp_treat, c(Temperature,Treatment), sep = "_", remove = FALSE) %>%
  mutate(temp_treat = as.factor(temp_treat)) %>%
  droplevels()


# PLOT phagocytes

# use summarySE to group data for plotting
cell_means <- summarySE(pcliv_summary, measurevar="Adj_Percent", groupvars=c("Temperature","Treatment"))

# plot, temperature  x axis colored by beads/ecoli treatment
plot <- ggplot(pcliv_summary, aes(x = Temperature, y = Adj_Percent))+
  theme_bw()+
  geom_jitter(aes(color = Treatment, fill = Treatment),
              position=position_dodge(width=0.3),
              alpha=0.2, pch = 21,
              color = "black") +
  geom_errorbar(data = cell_means, aes(x = Temperature, ymax = Adj_Percent+se, ymin = Adj_Percent-se, color = Treatment), width = .2, position = position_dodge(width=0.4)) +
  scale_color_manual(values = c("#ca7dcc",
                                "#1b98e0"))+
  geom_point(data = cell_means, mapping = aes(x=Temperature, y=Adj_Percent, color = lineage, fill = Treatment), size = 3.5, pch = 21, color = "black", position = position_dodge(width=0.4))+
  scale_fill_manual(values = c("#ca7dcc",
                                "#1b98e0"))+
  #scale_fill_manual(name = "Treatment",
  #                  breaks = c("L1","L2"),
  #                  values = cols_lineage)+
  #scale_color_manual(name = "Lineage",
  #                   breaks = c("L1","L2"),
  #                   values = cols_lineage)+
  xlab("Temperature")+
  ylab("Adjusted Percentage of Positive Cells")+
  theme(panel.border = element_rect(colour = "black", fill = NA, size = 1)) 
plot
#save plot
ggsave(plot, filename = "RELATIVE_PCLIV_dextrane.pdf", width=6, height=4, units=c("in"), useDingbats=FALSE)

```
```{r}
#PCLIV
#relative activity per SPECIES with beads compared to dextrane
library(tidyverse)
library(dplyr)
library(Rmisc)

# read in raw data from FlowJo
pcliv= read.csv("/Users/lysis/Downloads/pcliv_metadata.csv")

head(pcliv)
str(pcliv)

# clean up names of columns and make treatments of interest factors
pcliv_clean = pcliv %>%
  mutate(Temperature = as.factor(Temperature), ,
         Genotype = as.factor(Genotype), Replicate = as.factor(Replicate), Treatment = as.factor(Treatment)) %>%
  dplyr::rename(Num_Cells = Num_Cells) %>%
  dplyr::rename(Avg_Control = Average_Control) %>%
  dplyr::rename(Adj_Percent_A = Adjusted_Value_A) %>%
  dplyr::rename(Adj_Percent = Adjusted_Value_T)

str(pcliv_clean)

# subset data to only look at bead and Ecoli treatments, since data has been corrected to controls
pcliv_treatments = pcliv_clean %>%
  subset(Treatment == "beads"| Treatment == "dextrane" )

# calculate mean percent of cells across the three replicate measurements
pcliv_summary = pcliv_treatments %>%
  #group_by(Genotype, Temperature, Treatment) %>%
  #dplyr::summarize(mean_percent = mean(Adj_Percent_A)) %>%
  unite(temp_treat, c(Temperature,Treatment), sep = "_", remove = FALSE) %>%
  mutate(temp_treat = as.factor(temp_treat)) %>%
  droplevels()


# PLOT phagocytes

# use summarySE to group data for plotting
cell_means <- summarySE(pcliv_summary, measurevar="Adj_Percent_A", groupvars=c("Temperature","Treatment"))

# plot, temperature  x axis colored by beads/ecoli treatment
plot <- ggplot(pcliv_summary, aes(x = Temperature, y = Adj_Percent_A))+
  theme_bw()+
  geom_jitter(aes(color = Treatment, fill = Treatment),
              position=position_dodge(width=0.3),
              alpha=0.2, pch = 21,
              color = "black") +
  geom_errorbar(data = cell_means, aes(x = Temperature, ymax = Adj_Percent_A+se, ymin = Adj_Percent_A-se, color = Treatment), width = .2, position = position_dodge(width=0.4)) +
  scale_color_manual(values = c("#ca7dcc",
                                "#1b98e0"))+
  geom_point(data = cell_means, mapping = aes(x=Temperature, y=Adj_Percent_A, color = lineage, fill = Treatment), size = 3.5, pch = 21, color = "black", position = position_dodge(width=0.4))+
  scale_fill_manual(values = c("#ca7dcc",
                                "#1b98e0"))+
  #scale_fill_manual(name = "Treatment",
  #                  breaks = c("L1","L2"),
  #                  values = cols_lineage)+
  #scale_color_manual(name = "Lineage",
  #                   breaks = c("L1","L2"),
  #                   values = cols_lineage)+
  xlab("Temperature")+
  ylab("Relative Activity")+
  theme(panel.border = element_rect(colour = "black", fill = NA, size = 1)) 
plot
#save plot
ggsave(plot, filename = "RELATIVE_PCLIV_dextrane.pdf", width=6, height=4, units=c("in"), useDingbats=FALSE)

```
```{r}
#Looking if the average percentage of positives is significantly different
# subset data to only look at bead and Ecoli treatments, since data has been corrected to controls
pcliv_treatments = pcliv_clean %>%
  subset(Treatment == "beads" | Treatment == "ecoli"| Treatment == "dextrane")

# calculate mean percent of cells across the three replicate measurements
pcliv_summary = pcliv_treatments %>%
  group_by(Genotype, Temperature, Treatment) %>%
  #dplyr::summarize(Adj_Percent= mean(Adj_Percent)) %>%
  unite(temp_treat, c(Temperature,Treatment), sep = "_", remove = FALSE) %>%
  mutate(temp_treat = as.factor(temp_treat)) %>%
  droplevels()

# use summarySE to group data for plotting
cell_means <- summarySE(pcliv_summary, measurevar="Adj_Percent", groupvars=c("Temperature","Treatment","Genotype"))
```

```{r}
#one way Anova
pcliv.aov <- aov(Adj_Percent ~ Treatment, data = pcliv_beads)
summary(pcliv.aov)
#one way anova supports that treatment is having a significant affect on phagocytes normalized to temperature. p value is less than 2.e-16
```

```{r}
pcliv_beads = pcliv_clean %>%
  subset(Treatment == "beads")
```

```{r}
pclivbeads_ra.aov<-aov(Adjusted_Value_A ~ Temperature, data =pcliv_beads)
summary(pclivbeads_ra.aov)
```

```{r}
TukeyHSD(pclivbeads_gene.aov)
```


```{r}
#Checking if data meets anova assumptions
shapiro.test(x= as.numeric(pcliv_beads$Genotype))
#data normal
```
```{r}
kruskal.test(Adjusted_Value_A ~ Genotype, data = pcliv_beads)
#There is significance somewhere. p value is 7.895e-16
```
```{r}
library(FSA)
dunnTest(Adj_Percent ~ Treatment, data = pcliv_summary, method = "bonferroni")
#beads are different from dextrane and ecoli, dextrane is different from beads and ecoli
```
```{r}
dunnTest(Adj_Percent ~ Temperature, data = pcliv_summary, method = "bonferroni")
#on the average amount of phagocytes overall  temperature is not inducing a significant difference
```
```{r}
dunnTest(Adj_Percent ~ temp_treat, data = pcliv_summary, method = "bonferroni")
#no significant phagocytosis
```
```{r}
dunnTest(Adj_Percent ~ Genotype, data = pcliv_summary, method = "bonferroni")
#genotype has no effect
```
```{r}
#Looking if the relative percentage of positives is significantly different. Samples are adjusted to ambient temperature
# subset data to only look at bead and Ecoli treatments, since data has been corrected to controls
pcliv_treatments = pcliv_clean %>%
  subset(Treatment == "beads" | Treatment == "ecoli"| Treatment == "dextrane")

# calculate mean percent of cells across the three replicate measurements
pcliv_summary = pcliv_treatments %>%
  group_by(Genotype, Temperature, Treatment) %>%
  #dplyr::summarize(Adj_Percent_A = mean(Adj_Percent_A)) %>%
  unite(temp_treat, c(Temperature,Treatment), sep = "_", remove = FALSE) %>%
  mutate(temp_treat = as.factor(temp_treat)) %>%
  droplevels()

# use summarySE to group data for plotting
cell_means <- summarySE(pcliv_summary, measurevar="Adj_Percent_A", groupvars=c("Temperature","Treatment","Genotype"))
```

```{r}
pcliv.aov <- aov(Adj_Percent_A~ Treatment, data = pcliv_summary)
summary(pcliv.aov)
#anova sees significance
```

```{r}
shapiro.test(x= pcliv_summary$Adj_Percent_A)
#data isn't normal
```
```{r}
kruskal.test(Adj_Percent_A~ temp_treat, data = pcliv_summary)
#There is significance somewhere. p value is 0.0002892
```
```{r}
library(FSA)
dunnTest(Adj_Percent_A ~ temp_treat, data = pcliv_summary, method = "bonferroni")
#dextran changes but nothing else
```

```{r}
dunnTest(Adj_Percent_A ~ Genotype, data = pcliv_summary, method = "bonferroni")
#no genotypic differences

```

