---
title: "GO_term_venndiagram"
author: "allyson_demerlis"
date: "2024-02-23"
output: html_document
---
# load libraries
```{r}
library(tidyverse)
library(ggvenn)
library(cowplot)
```

# L2FC 

## All L2FC
```{r}
# Variable vs. Initial
MWU_result_BP_VariablevInitial=read.csv("L2FC/MWU_BP_Treated_vs_Initial_fc.csv", sep = "")
MWU_result_BP_VariablevInitial %>% 
  filter(p.adj < 0.05) %>% 
  mutate(GO_category = "BP", Contrast = "Variable_vs_Initial") -> MWU_result_BP_VariablevInitial_05

MWU_result_MF_VariablevInitial=read.csv("L2FC/MWU_MF_Treated_vs_Initial_fc.csv", sep = "")
MWU_result_MF_VariablevInitial %>% 
  filter(p.adj < 0.05) %>% 
  mutate(GO_category = "MF", Contrast = "Variable_vs_Initial") -> MWU_result_MF_VariablevInitial_05

MWU_result_CC_VariablevInitial=read.csv("L2FC/MWU_CC_Treated_vs_Initial_fc.csv", sep = "")
MWU_result_CC_VariablevInitial %>% 
  filter(p.adj < 0.05) %>% 
  mutate(GO_category = "CC", Contrast = "Variable_vs_Initial") -> MWU_result_CC_VariablevInitial_05

# Variable vs. Control
MWU_result_BP_VariablevControl=read.csv("L2FC/MWU_BP_Treated_vs_Untreated_fc.csv", sep = "")
MWU_result_BP_VariablevControl %>% 
  filter(p.adj < 0.05) %>% 
  mutate(GO_category = "BP", Contrast = "Variable_vs_Control") -> MWU_result_BP_VariablevControl_05

MWU_result_MF_VariablevControl=read.csv("L2FC/MWU_MF_Treated_vs_Untreated_fc.csv", sep = "")
MWU_result_MF_VariablevControl %>% 
  filter(p.adj < 0.05) %>% 
  mutate(GO_category = "MF", Contrast = "Variable_vs_Control") -> MWU_result_MF_VariablevControl_05

MWU_result_CC_VariablevControl=read.csv("L2FC/MWU_CC_Treated_vs_Untreated_fc.csv", sep = "")
MWU_result_CC_VariablevControl %>% 
  filter(p.adj < 0.05) %>% 
  mutate(GO_category = "CC", Contrast = "Variable_vs_Control") -> MWU_result_CC_VariablevControl_05

# Control vs. Initial
MWU_result_BP_ControlvInitial=read.csv("L2FC/MWU_BP_Untreated_vs_Initial_fc.csv", sep = "")
MWU_result_BP_ControlvInitial %>% 
  filter(p.adj < 0.05) %>% 
  mutate(GO_category = "BP", Contrast = "Control_vs_Initial") -> MWU_result_BP_ControlvInitial_05

MWU_result_MF_ControlvInitial=read.csv("L2FC/MWU_MF_Untreated_vs_Initial_fc.csv", sep = "")
MWU_result_MF_ControlvInitial %>% 
  filter(p.adj < 0.05) %>% 
  mutate(GO_category = "MF", Contrast = "Control_vs_Initial") -> MWU_result_MF_ControlvInitial_05

MWU_result_CC_ControlvInitial=read.csv("L2FC/MWU_CC_Untreated_vs_Initial_fc.csv", sep = "")
MWU_result_CC_ControlvInitial %>% 
  filter(p.adj < 0.05) %>% 
  mutate(GO_category = "CC", Contrast = "Control_vs_Initial") -> MWU_result_CC_ControlvInitial_05


rbind(MWU_result_BP_VariablevInitial_05, MWU_result_MF_VariablevInitial_05, MWU_result_CC_VariablevInitial_05, MWU_result_BP_VariablevControl_05, MWU_result_MF_VariablevControl_05, MWU_result_CC_VariablevControl_05, MWU_result_BP_ControlvInitial_05, MWU_result_MF_ControlvInitial_05, MWU_result_CC_ControlvInitial_05) %>% 
  group_by(GO_category, Contrast) %>% 
  top_n(5, abs(delta.rank)) %>% 
  mutate(Direction = case_when(delta.rank > 0 ~ "Up",
                               delta.rank < 0 ~ "Down")) %>% 
  mutate(GO_category = factor(GO_category, levels = c("BP", "MF", "CC"))) %>% 
  ggplot(., aes(x = reorder(name, delta.rank), y = Contrast)) +
  geom_point(aes(size = nseqs, col = Direction)) +
  theme_classic() +
  labs(x = "GO Term", y = "Contrast", size = "Number of Genes") +
  facet_wrap(~GO_category, scales = "free", ncol = 1) +
  scale_color_manual(values = c("Up" = "red", "Down" = "blue")) +
  coord_flip() 
#ggsave("top10_GOterms_allcontrasts_L2FC.pdf", width = 8, height = 12)
```

## Variable GO terms (removing control vs. initial overlaps)
```{r}
# code from venn diagram 

#BP
MWU_result_BP_VariablevInitial_05_name <- MWU_result_BP_VariablevInitial_05$name
MWU_result_BP_VariablevControl_05_name <- MWU_result_BP_VariablevControl_05$name
MWU_result_BP_ControlvInitial_05_name <- MWU_result_BP_ControlvInitial_05$name

pairwise_bp=list("Variable vs. Initial" = MWU_result_BP_VariablevInitial_05_name, "Variable vs. Control" = MWU_result_BP_VariablevControl_05_name, "Control vs. Initial" = MWU_result_BP_ControlvInitial_05_name)

 v.table <- gplots::venn(pairwise_bp)

print(v.table)

    all_intersections <- attr(v.table, "intersections")
    for (comparison in names(all_intersections)) {
      cat(comparison, "\n")
      print(all_intersections[[comparison]])
    }
    
length(all_intersections$`Variable vs. Control`) #60

GO_BP_VvC <- all_intersections$`Variable vs. Control`

length(all_intersections$`Variable vs. Initial`) #237

GO_BP_VvI <- all_intersections$`Variable vs. Initial`

length( all_intersections$`Variable vs. Initial:Variable vs. Control`) #9 

GO_BP_V <- all_intersections$`Variable vs. Initial:Variable vs. Control`

variable_GO_BP <- c(GO_BP_V, GO_BP_VvC, GO_BP_VvI) %>% 
  as.data.frame() %>%  #583 total 
  dplyr::rename(name = ".")

variable_GO_BP_stats <-rbind(MWU_result_BP_VariablevInitial_05, MWU_result_BP_VariablevControl_05, MWU_result_BP_ControlvInitial_05) %>% 
  right_join(., variable_GO_BP) 

#MF
MWU_result_MF_VariablevInitial_05_name <- MWU_result_MF_VariablevInitial_05$name
MWU_result_MF_VariablevControl_05_name <- MWU_result_MF_VariablevControl_05$name
MWU_result_MF_ControlvInitial_05_name <- MWU_result_MF_ControlvInitial_05$name

pairwise_mf=list("Variable vs. Initial" = MWU_result_MF_VariablevInitial_05_name, "Variable vs. Control" = MWU_result_MF_VariablevControl_05_name, "Control vs. Initial" = MWU_result_MF_ControlvInitial_05_name)

 v.table <- gplots::venn(pairwise_mf)

print(v.table)

    all_intersections <- attr(v.table, "intersections")
    for (comparison in names(all_intersections)) {
      cat(comparison, "\n")
      print(all_intersections[[comparison]])
    }
    
length(all_intersections$`Variable vs. Control`) #4

GO_MF_VvC <- all_intersections$`Variable vs. Control`

length(all_intersections$`Variable vs. Initial`) #38

GO_MF_VvI <- all_intersections$`Variable vs. Initial`

length( all_intersections$`Variable vs. Initial:Variable vs. Control`) #1

GO_MF_V <- all_intersections$`Variable vs. Initial:Variable vs. Control`

variable_GO_MF <- c(GO_MF_V, GO_MF_VvC, GO_MF_VvI) %>% 
  as.data.frame() %>%  #43 total 
  dplyr::rename(name = ".")

variable_GO_MF_stats <-rbind(MWU_result_MF_VariablevInitial_05, MWU_result_MF_VariablevControl_05, MWU_result_MF_ControlvInitial_05) %>% 
  right_join(., variable_GO_MF) 

#CC
MWU_result_CC_VariablevInitial_05_name <- MWU_result_CC_VariablevInitial_05$name
MWU_result_CC_VariablevControl_05_name <- MWU_result_CC_VariablevControl_05$name
MWU_result_CC_ControlvInitial_05_name <- MWU_result_CC_ControlvInitial_05$name

pairwise_mf=list("Variable vs. Initial" = MWU_result_CC_VariablevInitial_05_name, "Variable vs. Control" = MWU_result_CC_VariablevControl_05_name, "Control vs. Initial" = MWU_result_CC_ControlvInitial_05_name)

 v.table <- gplots::venn(pairwise_mf)

print(v.table)

    all_intersections <- attr(v.table, "intersections")
    for (comparison in names(all_intersections)) {
      cat(comparison, "\n")
      print(all_intersections[[comparison]])
    }
    
length(all_intersections$`Variable vs. Control`) #32

GO_CC_VvC <- all_intersections$`Variable vs. Control`

length(all_intersections$`Variable vs. Initial`) #34

GO_CC_VvI <- all_intersections$`Variable vs. Initial`

length( all_intersections$`Variable vs. Initial:Variable vs. Control`) #4

GO_CC_V <- all_intersections$`Variable vs. Initial:Variable vs. Control`

variable_GO_CC <- c(GO_CC_V, GO_CC_VvC, GO_CC_VvI) %>% 
  as.data.frame() %>%  #70 total 
  dplyr::rename(name = ".")

variable_GO_CC_stats <-rbind(MWU_result_CC_VariablevInitial_05, MWU_result_CC_VariablevControl_05, MWU_result_CC_ControlvInitial_05) %>% 
  right_join(., variable_GO_CC) 

# rbind(variable_GO_BP_stats, variable_GO_MF_stats, variable_GO_CC_stats) %>% 
#   write_csv("Acer_host_sigGOterms_uniquevariable.csv")

# bind them all together

rbind(variable_GO_BP_stats, variable_GO_MF_stats, variable_GO_CC_stats) %>% 
  group_by(GO_category, Contrast) %>% 
  top_n(5, abs(delta.rank)) %>% 
  mutate(Direction = case_when(delta.rank > 0 ~ "Up",
                               delta.rank < 0 ~ "Down")) %>% 
  mutate(Contrast = case_when(Contrast == "Variable_vs_Control" ~ "Variable vs. Control",
                              Contrast == "Variable_vs_Initial" ~ "Variable vs. Initial")) %>% 
  mutate(GO_category = factor(GO_category, levels = c("BP", "MF", "CC"))) %>% 
  ggplot(., aes(x = reorder(name, delta.rank), y = Contrast)) +
  geom_point(aes(size = nseqs, col = Direction)) +
  theme_classic() +
  labs(x = NULL, y=NULL, size = "Genes") +
  facet_wrap(~GO_category, scales = "free_y", ncol = 1) +
  scale_color_manual(values = c("Up" = "red", "Down" = "blue")) +
  coord_flip() + 
  theme(text = element_text(size = 13))  +
  scale_size(range = c(2, 5), breaks = c(10, 50, 100)) 
#ggsave("top10_GOterms_unqiuevariable_L2FC.pdf", width = 6, height = 10)
```


# lpv

```{r}
# Variable vs. Initial
MWU_result_BP_VariablevInitial=read.csv("lpv/MWU_BP_Treated_vs_Initial_lpv.csv", sep = "")
MWU_result_BP_VariablevInitial %>% 
  filter(p.adj < 0.05) %>% 
  mutate(GO_category = "BP", Contrast = "Variable_vs_Initial") -> MWU_result_BP_VariablevInitial_05

MWU_result_MF_VariablevInitial=read.csv("lpv/MWU_MF_Treated_vs_Initial_lpv.csv", sep = "")
MWU_result_MF_VariablevInitial %>% 
  filter(p.adj < 0.05) %>% 
  mutate(GO_category = "MF", Contrast = "Variable_vs_Initial") -> MWU_result_MF_VariablevInitial_05

MWU_result_CC_VariablevInitial=read.csv("lpv/MWU_CC_Treated_vs_Initial_lpv.csv", sep = "")
MWU_result_CC_VariablevInitial %>% 
  filter(p.adj < 0.05) %>% 
  mutate(GO_category = "CC", Contrast = "Variable_vs_Initial") -> MWU_result_CC_VariablevInitial_05

# Variable vs. Control
MWU_result_BP_VariablevControl=read.csv("lpv/MWU_BP_Treated_vs_Untreated_lpv.csv", sep = "")
MWU_result_BP_VariablevControl %>% 
  filter(p.adj < 0.05) %>% 
  mutate(GO_category = "BP", Contrast = "Variable_vs_Control") -> MWU_result_BP_VariablevControl_05

MWU_result_MF_VariablevControl=read.csv("lpv/MWU_MF_Treated_vs_Untreated_lpv.csv", sep = "")
MWU_result_MF_VariablevControl %>% 
  filter(p.adj < 0.05) %>% 
  mutate(GO_category = "MF", Contrast = "Variable_vs_Control") -> MWU_result_MF_VariablevControl_05

MWU_result_CC_VariablevControl=read.csv("lpv/MWU_CC_Treated_vs_Untreated_lpv.csv", sep = "")
MWU_result_CC_VariablevControl %>% 
  filter(p.adj < 0.05) %>% 
  mutate(GO_category = "CC", Contrast = "Variable_vs_Control") -> MWU_result_CC_VariablevControl_05

# Control vs. Initial
MWU_result_BP_ControlvInitial=read.csv("lpv/MWU_BP_Untreated_vs_Initial_lpv.csv", sep = "")
MWU_result_BP_ControlvInitial %>% 
  filter(p.adj < 0.05) %>% 
  mutate(GO_category = "BP", Contrast = "Control_vs_Initial") -> MWU_result_BP_ControlvInitial_05

MWU_result_MF_ControlvInitial=read.csv("lpv/MWU_MF_Untreated_vs_Initial_lpv.csv", sep = "")
MWU_result_MF_ControlvInitial %>% 
  filter(p.adj < 0.05) %>% 
  mutate(GO_category = "MF", Contrast = "Control_vs_Initial") -> MWU_result_MF_ControlvInitial_05

MWU_result_CC_ControlvInitial=read.csv("lpv/MWU_CC_Untreated_vs_Initial_lpv.csv", sep = "")
MWU_result_CC_ControlvInitial %>% 
  filter(p.adj < 0.05) %>% 
  mutate(GO_category = "CC", Contrast = "Control_vs_Initial") -> MWU_result_CC_ControlvInitial_05


rbind(MWU_result_BP_VariablevInitial_05, MWU_result_MF_VariablevInitial_05, MWU_result_CC_VariablevInitial_05, MWU_result_BP_VariablevControl_05, MWU_result_MF_VariablevControl_05, MWU_result_CC_VariablevControl_05, MWU_result_BP_ControlvInitial_05, MWU_result_MF_ControlvInitial_05, MWU_result_CC_ControlvInitial_05) %>% 
  group_by(GO_category, Contrast) %>% 
  top_n(5, abs(delta.rank)) %>% 
  mutate(Direction = case_when(delta.rank > 0 ~ "Up",
                               delta.rank < 0 ~ "Down")) %>% 
  mutate(GO_category = factor(GO_category, levels = c("BP", "MF", "CC"))) %>% 
  ggplot(., aes(x = reorder(name, delta.rank), y = Contrast)) +
  geom_point(aes(size = nseqs, col = Direction)) +
  theme_classic() +
  labs(x = "GO Term", y = "Contrast", size = "Number of Genes") +
  facet_wrap(~GO_category, scales = "free", ncol = 1) +
  scale_color_manual(values = c("Up" = "red", "Down" = "blue")) +
  coord_flip() 
#ggsave("top10_GOterms_allcontrasts_lpv.pdf", width = 8, height = 12)
```


## Variable GO terms (removing control vs. initial overlaps)
```{r}
# code from venn diagram 

#BP
MWU_result_BP_VariablevInitial_05_name <- MWU_result_BP_VariablevInitial_05$name
MWU_result_BP_VariablevControl_05_name <- MWU_result_BP_VariablevControl_05$name
MWU_result_BP_ControlvInitial_05_name <- MWU_result_BP_ControlvInitial_05$name

pairwise_bp=list("Variable vs. Initial" = MWU_result_BP_VariablevInitial_05_name, "Variable vs. Control" = MWU_result_BP_VariablevControl_05_name, "Control vs. Initial" = MWU_result_BP_ControlvInitial_05_name)

 v.table <- gplots::venn(pairwise_bp)

print(v.table)

    all_intersections <- attr(v.table, "intersections")
    for (comparison in names(all_intersections)) {
      cat(comparison, "\n")
      print(all_intersections[[comparison]])
    }
    
length(all_intersections$`Variable vs. Control`) #60

GO_BP_VvC <- all_intersections$`Variable vs. Control`

length(all_intersections$`Variable vs. Initial`) #237

GO_BP_VvI <- all_intersections$`Variable vs. Initial`

length( all_intersections$`Variable vs. Initial:Variable vs. Control`) #9 

GO_BP_V <- all_intersections$`Variable vs. Initial:Variable vs. Control`

variable_GO_BP <- c(GO_BP_V, GO_BP_VvC, GO_BP_VvI) %>% 
  as.data.frame() %>%  #583 total 
  dplyr::rename(name = ".")

variable_GO_BP_stats <-rbind(MWU_result_BP_VariablevInitial_05, MWU_result_BP_VariablevControl_05, MWU_result_BP_ControlvInitial_05) %>% 
  right_join(., variable_GO_BP) 

#MF
MWU_result_MF_VariablevInitial_05_name <- MWU_result_MF_VariablevInitial_05$name
MWU_result_MF_VariablevControl_05_name <- MWU_result_MF_VariablevControl_05$name
MWU_result_MF_ControlvInitial_05_name <- MWU_result_MF_ControlvInitial_05$name

pairwise_mf=list("Variable vs. Initial" = MWU_result_MF_VariablevInitial_05_name, "Variable vs. Control" = MWU_result_MF_VariablevControl_05_name, "Control vs. Initial" = MWU_result_MF_ControlvInitial_05_name)

 v.table <- gplots::venn(pairwise_mf)

print(v.table)

    all_intersections <- attr(v.table, "intersections")
    for (comparison in names(all_intersections)) {
      cat(comparison, "\n")
      print(all_intersections[[comparison]])
    }
    
length(all_intersections$`Variable vs. Control`) #4

GO_MF_VvC <- all_intersections$`Variable vs. Control`

length(all_intersections$`Variable vs. Initial`) #38

GO_MF_VvI <- all_intersections$`Variable vs. Initial`

length( all_intersections$`Variable vs. Initial:Variable vs. Control`) #1

GO_MF_V <- all_intersections$`Variable vs. Initial:Variable vs. Control`

variable_GO_MF <- c(GO_MF_V, GO_MF_VvC, GO_MF_VvI) %>% 
  as.data.frame() %>%  #43 total 
  dplyr::rename(name = ".")

variable_GO_MF_stats <-rbind(MWU_result_MF_VariablevInitial_05, MWU_result_MF_VariablevControl_05, MWU_result_MF_ControlvInitial_05) %>% 
  right_join(., variable_GO_MF) 

#CC
MWU_result_CC_VariablevInitial_05_name <- MWU_result_CC_VariablevInitial_05$name
MWU_result_CC_VariablevControl_05_name <- MWU_result_CC_VariablevControl_05$name
MWU_result_CC_ControlvInitial_05_name <- MWU_result_CC_ControlvInitial_05$name

pairwise_mf=list("Variable vs. Initial" = MWU_result_CC_VariablevInitial_05_name, "Variable vs. Control" = MWU_result_CC_VariablevControl_05_name, "Control vs. Initial" = MWU_result_CC_ControlvInitial_05_name)

 v.table <- gplots::venn(pairwise_mf)

print(v.table)

    all_intersections <- attr(v.table, "intersections")
    for (comparison in names(all_intersections)) {
      cat(comparison, "\n")
      print(all_intersections[[comparison]])
    }
    
length(all_intersections$`Variable vs. Control`) #32

GO_CC_VvC <- all_intersections$`Variable vs. Control`

length(all_intersections$`Variable vs. Initial`) #34

GO_CC_VvI <- all_intersections$`Variable vs. Initial`

length( all_intersections$`Variable vs. Initial:Variable vs. Control`) #4

GO_CC_V <- all_intersections$`Variable vs. Initial:Variable vs. Control`

variable_GO_CC <- c(GO_CC_V, GO_CC_VvC, GO_CC_VvI) %>% 
  as.data.frame() %>%  #70 total 
  dplyr::rename(name = ".")

variable_GO_CC_stats <-rbind(MWU_result_CC_VariablevInitial_05, MWU_result_CC_VariablevControl_05, MWU_result_CC_ControlvInitial_05) %>% 
  right_join(., variable_GO_CC) 

# rbind(variable_GO_BP_stats, variable_GO_MF_stats, variable_GO_CC_stats) %>%
#   write_csv("Acer_host_lpv_sigGOterms_uniquevariable.csv")


# bind them all together

rbind(variable_GO_BP_stats, variable_GO_MF_stats, variable_GO_CC_stats) %>% 
  group_by(GO_category, Contrast) %>% 
  top_n(5, abs(delta.rank)) %>% 
  mutate(Direction = case_when(delta.rank > 0 ~ "Up",
                               delta.rank < 0 ~ "Down")) %>% 
  mutate(GO_category = factor(GO_category, levels = c("BP", "MF", "CC"))) %>% 
  ggplot(., aes(x = reorder(name, delta.rank), y = Contrast)) +
  geom_point(aes(size = nseqs, col = Direction)) +
  theme_classic() +
  labs(x = "GO Term", y = "Contrast", size = "Number of Genes") +
  facet_wrap(~GO_category, scales = "free", ncol = 1) +
  scale_color_manual(values = c("Up" = "red", "Down" = "blue")) +
  coord_flip() 
#ggsave("top10_GOterms_unqiuevariable_lpv.pdf", width = 8, height = 12)
```





