---
title: "colorscores"
author: "allyson_demerlis"
date: "2022-11-30"
output: html_document
---

# Read in data and R packages
```{r}
library(tidyverse)
library(readxl)
library(rstatix)
library(plotrix)
library(ggpubr)
library(cowplot)
library(FSA) #for Summarize
library(lme4)
library(car)
library(MASS)
library(emmeans)

Rscoredata <- read_xlsx("data_rscores.xlsx") 

Rscoredata %>% 
  rename(`Photo ID` = `Image #`) %>% 
  rename(Date = `Date (Folder Name)`) -> Rscoredata

# Only use the R-score data from the treatment period dates
initialphotos <- read_xlsx("photo_metadata.xlsx")
april18 <- read_xlsx("photo_metadata.xlsx", sheet = "april 18")

# june21 <- read_xlsx("photo_metadata.xlsx", sheet = "june 21")
# july8 <- read_xlsx("photo_metadata.xlsx", sheet = "july 8")

coral_metadata <- read_csv("../metadata.csv")

coral_metadata %>% 
  dplyr::select(Species:CBASS_tank) -> coral_metadata
```

# Tidy data
```{r}
str(initialphotos) 
initialphotos %>% 
  dplyr::select(`Photo ID`:`Coral Position`) -> initialphotos

str(april18)
april18 %>% 
  dplyr::select(`Photo ID`:`Coral Position`) -> april18

# str(june21) 
# june21%>% 
#   dplyr::select(`Photo ID`:`Coral Position`) -> june21
# 
# str(july8)
# july8 %>% 
#   dplyr::select(`Photo ID`:`Coral Position`) -> july8

full_join(initialphotos, april18) -> allRscores

allRscores

#Tank column depends on time point, as the tank assignments changed throughout timeline. But, should be able to use the Puck ID + Species as the unique identifier

allRscores %>% 
  mutate(Species = case_when(Species == "Acer" ~ "Acropora cervicornis",
                             Species == "Pcli" ~ "Pseudodiploria clivosa")) -> allRscores

allRscores %>% 
  rename(ID = `Puck ID`) -> allRscores #821 rows

full_join(allRscores, coral_metadata, by = c("Species", "ID")) %>% 
  drop_na(`Photo ID`)  -> allmetadata #821 rows 

full_join(allmetadata, Rscoredata, by = c("Date", "Photo ID", "Coral Position")) -> Rintensity_withmetadata

Rintensity_withmetadata %>% 
  dplyr::select(!Genotype) -> Rintensity_withmetadata

Rintensity_withmetadata$month <- format(Rintensity_withmetadata$Date, "%m")

Rintensity_withmetadata$Date <- as.factor(Rintensity_withmetadata$Date)

Rintensity_withmetadata$month <- as.factor(Rintensity_withmetadata$month)

Rintensity_withmetadata %>% 
  group_by(ID, Species, Colony, Treatment, month) %>% 
  mutate(mean_Rintensity_percoral = mean(Mean)) -> Rintensity_withmetadata

# Rintensity_withmetadata %>% 
#   filter(is.na(Species)) #photo 4709 is a duplicate from photo 4711 so I already have these values in the spreadsheet

Rintensity_withmetadata %>% 
  drop_na(ID) -> Rintensity_withmetadata

#write_csv(Rintensity_withmetadata, "Rintensity_withmetadata.csv")

 # Calculate days relative to start of treatment
Rintensity_withmetadata %>% 
  ungroup() %>% 
  dplyr::select(Date:Species, Colony:Treatment_Tank, mean_Rintensity_percoral) %>% 
  distinct() %>% 
  mutate(Date = as.Date(as.character(Date), format = "%Y-%m-%d")) %>% 
  mutate(Days_Relative = as.numeric(Date - as.Date("2022-03-24"))) -> Rintensity_tidydata
``` 

# Boxplot of raw values
```{r}
  ggplot(Rintensity_withmetadata,aes(x = month, y= mean_Rintensity_percoral, fill = Treatment)) + 
  geom_boxplot() + 
  theme_classic() +
  facet_wrap(~Species, scales = "free") +
  ylim(0, 255) +
  labs(y = "R-Intensity", x= "Time Point") +
  theme(text = element_text(size = 13)) + 
  scale_fill_manual(labels=c("Variable", "Control"), values = c("#F54A34", "#60DBDB"))
#ggsave("Rintensityovertime_byspecies.pdf")
```

# mean value per time point
## Acer
```{r}
p1<-Rintensity_withmetadata %>%
  filter(Species == "Acropora cervicornis") %>% 
  mutate(month = as.numeric(as.character(month))) %>% 
  dplyr::select(Species, Colony, Treatment, month, mean_Rintensity_percoral) %>% 
  distinct() %>% 
  ungroup() %>% 
  group_by(Species, Treatment, month) %>% 
  summarise(mean_Rintensity = mean(mean_Rintensity_percoral), se_Rintensity = std.error(mean_Rintensity_percoral)) %>% 
  ggplot(.,aes(x = month, y= mean_Rintensity, color = Treatment)) + 
  geom_point() + 
  geom_line() +
  geom_errorbar(aes(ymin = mean_Rintensity - se_Rintensity, ymax = mean_Rintensity + se_Rintensity), width = 0.1) + 
  theme_classic() +
  ylim(0, 255) +
  scale_x_continuous(breaks = seq(3, 4, by = 1)) +
  labs(y = "R-Intensity", x= "Time Point", title = "A. cervicornis") +
  theme(text = element_text(size = 13)) + 
  scale_color_manual(labels=c("Variable", "Control"), values = c("#F54A34", "#60DBDB"))
```

## Pcli
```{r}
p2<-Rintensity_withmetadata %>%
  filter(Species == "Pseudodiploria clivosa") %>% 
  mutate(month = as.numeric(as.character(month))) %>% 
  dplyr::select(Species, Colony, Treatment, month, mean_Rintensity_percoral) %>% 
  distinct() %>% 
  ungroup() %>% 
  group_by(Species, Treatment, month) %>% 
  summarise(mean_Rintensity = mean(mean_Rintensity_percoral), se_Rintensity = std.error(mean_Rintensity_percoral)) %>% 
  ggplot(.,aes(x = month, y= mean_Rintensity, color = Treatment)) + 
  geom_point() + 
  geom_line() +
  geom_errorbar(aes(ymin = mean_Rintensity - se_Rintensity, ymax = mean_Rintensity + se_Rintensity), width = 0.1) + 
  theme_classic() +
  ylim(0, 255) +
  scale_x_continuous(breaks = seq(3, 4, by = 1)) +
  labs(y = "R-Intensity", x= "Time Point", title = "P. clivosa") +
  theme(text = element_text(size = 13)) + 
  scale_color_manual(labels=c("Variable", "Control"), values = c("#F54A34", "#60DBDB"))
```


# plot
```{r}
plot_grid(p1, p2, nrow=1,
       labels = c("A", "B"),       # Add panel labels
  label_size = 14)
ggsave("treatmentRintensity_bothspecies.pdf", width=10, height=5)
```


# normalize to initial value

## Acer
```{r}
p1<-Rintensity_withmetadata %>%
  filter(Species == "Acropora cervicornis") %>% 
  mutate(month = as.numeric(as.character(month))) %>% 
  dplyr::select(Species, Colony, Treatment, month, mean_Rintensity_percoral) %>% 
  distinct() %>% 
  ungroup() %>% 
  pivot_wider(names_from = month, values_from = mean_Rintensity_percoral) %>% 
  dplyr::rename(initial_R = `3`, final_R = `4`) %>% 
  mutate(norm_R_T0 = initial_R/initial_R, norm_R_T1 = -final_R/initial_R) %>% 
  drop_na(norm_R_T1) %>% 
  pivot_longer(norm_R_T0:norm_R_T1, names_to = "timepoint", values_to = "R_intensity_norm") %>% 
  mutate(timepoint = case_when(timepoint == "norm_R_T0" ~ 0, 
                               timepoint == "norm_R_T1" ~ 1)) %>% 
  group_by(Species, Treatment, timepoint) %>% 
  summarise(mean_Rintensity = mean(R_intensity_norm), se_Rintensity = std.error(R_intensity_norm)) %>% 
  ggplot(.,aes(x = timepoint, y= mean_Rintensity, color = Treatment)) + 
  geom_point() + 
  geom_line() +
  geom_errorbar(aes(ymin = mean_Rintensity - se_Rintensity, ymax = mean_Rintensity + se_Rintensity), width = 0.1) + 
  theme_classic() +
  scale_x_continuous(breaks = seq(0, 1, by = 1)) +
  labs(y = "Normalized R-Intensity", x= "Time Point", title = "A. cervicornis") +
  theme(text = element_text(size = 13)) + 
  scale_color_manual(labels=c("Variable", "Control"), values = c("#F54A34", "#60DBDB")) +
  ylim(-2, 1)
```

## Pcli
```{r}
p2<-Rintensity_withmetadata %>%
  filter(Species == "Pseudodiploria clivosa") %>% 
  mutate(month = as.numeric(as.character(month))) %>% 
  dplyr::select(Species, Colony, Treatment, month, mean_Rintensity_percoral) %>% 
  distinct() %>% 
  ungroup() %>% 
  pivot_wider(names_from = month, values_from = mean_Rintensity_percoral) %>% 
  dplyr::rename(initial_R = `3`, final_R = `4`) %>% 
  mutate(norm_R_T0 = initial_R/initial_R, norm_R_T1 = -final_R/initial_R) %>% 
  drop_na(norm_R_T1) %>% 
  pivot_longer(norm_R_T0:norm_R_T1, names_to = "timepoint", values_to = "R_intensity_norm") %>% 
  mutate(timepoint = case_when(timepoint == "norm_R_T0" ~ 0, 
                               timepoint == "norm_R_T1" ~ 1)) %>% 
  group_by(Species, Treatment, timepoint) %>% 
  summarise(mean_Rintensity = mean(R_intensity_norm), se_Rintensity = std.error(R_intensity_norm)) %>% 
  ggplot(.,aes(x = timepoint, y= mean_Rintensity, color = Treatment)) + 
  geom_point() + 
  geom_line() +
  geom_errorbar(aes(ymin = mean_Rintensity - se_Rintensity, ymax = mean_Rintensity + se_Rintensity), width = 0.1) + 
  theme_classic() +
  scale_x_continuous(breaks = seq(0, 1, by = 1)) +
  labs(y = "Normalized R-Intensity", x= "Time Point", title = "P. clivosa") +
  theme(text = element_text(size = 13)) + 
  scale_color_manual(labels=c("Variable", "Control"), values = c("#F54A34", "#60DBDB")) +
  ylim(-2, 1)
```

# plot
```{r}
plot_grid(p1, p2, nrow=1,
       labels = c("A", "B"),       # Add panel labels
  label_size = 14)
ggsave("treatment_normalized_Rintensity_bothspecies.pdf", width=10, height=5)
```

# Kruskal-Wallis Test

## Acer
```{r}
Rintensity_withmetadata %>%
  filter(Species == "Acropora cervicornis") %>% 
  mutate(month = as.numeric(as.character(month))) %>% 
  dplyr::select(Species, Colony, Treatment, month, mean_Rintensity_percoral) %>% 
  distinct() %>% 
  ungroup() %>% 
  pivot_wider(names_from = month, values_from = mean_Rintensity_percoral) %>% 
  dplyr::rename(initial_R = `3`, final_R = `4`) %>% 
  mutate(norm_R_T0 = initial_R/initial_R, norm_R_T1 = final_R/initial_R) %>% #don't need the negative for this -- was just for visualization
  drop_na(norm_R_T1) %>% 
  pivot_longer(norm_R_T0:norm_R_T1, names_to = "timepoint", values_to = "R_intensity_norm") %>% 
  filter(timepoint == "norm_R_T1") -> Acer_R_norm

Acer_R_norm %>% 
  group_by(Treatment) %>% 
  summarise(count = n()) #variable=63 and control=70

summary(aov(R_intensity_norm ~ Treatment, data = Acer_R_norm)) #significant

Acer_lm <- aov(R_intensity_norm ~ Treatment, data = Acer_R_norm)
shapiro_test(Acer_lm$residuals) # significant
leveneTest(R_intensity_norm ~ Treatment, data = Acer_R_norm) #significant

# run non-parametric Kruskal-Wallis Test
kruskal_test(R_intensity_norm ~ Treatment, data = Acer_R_norm) # significant
```
## Pcli
```{r}
Rintensity_withmetadata %>%
  filter(Species == "Pseudodiploria clivosa") %>% 
  mutate(month = as.numeric(as.character(month))) %>% 
  dplyr::select(Species, Colony, Treatment, month, mean_Rintensity_percoral) %>% 
  distinct() %>% 
  ungroup() %>% 
  pivot_wider(names_from = month, values_from = mean_Rintensity_percoral) %>% 
  dplyr::rename(initial_R = `3`, final_R = `4`) %>% 
  mutate(norm_R_T0 = initial_R/initial_R, norm_R_T1 = final_R/initial_R) %>% #don't need the negative for this -- was just for visualization
  drop_na(norm_R_T1) %>% 
  pivot_longer(norm_R_T0:norm_R_T1, names_to = "timepoint", values_to = "R_intensity_norm") %>% 
  filter(timepoint == "norm_R_T1") -> Pcli_R_norm

Pcli_R_norm %>% 
  group_by(Treatment) %>% 
  summarise(count = n()) #variable=70 and control=72

summary(aov(R_intensity_norm ~ Treatment, data = Pcli_R_norm)) # not significant

Pcli_lm <- aov(R_intensity_norm ~ Treatment, data = Pcli_R_norm)
shapiro_test(Pcli_lm$residuals) # significant
leveneTest(R_intensity_norm ~ Treatment, data = Pcli_R_norm) # not significant

# run non-parametric Kruskal-Wallis Test
kruskal_test(R_intensity_norm ~ Treatment, data = Pcli_R_norm) # not significant
```
