---
title: "Acer_PCA"
author: "allyson_demerlis"
date: "2023-11-24"
output: html_document
---

```{r}
library(DESeq2)
library(tidyverse)
library(factoextra)
library(cowplot)

load("RData_files/initial_fullddsdesigncountsVsdcountsWGCNA.RData")
```


```{r}
pca <- prcomp(t(assay(Vsd)))
summary(pca)
fviz_eig(pca)
```

Note: the data going into these PCAs is after the outlier removal step using arrayQualityMetrics
```{r}
plotPCA(Vsd, intgroup = c("Treatment"))
plotPCA(Vsd, intgroup = c("Genotype"))
plotPCA(Vsd, intgroup = c("Treatment", "Genotype"))

vst_PCAdata <- plotPCA(Vsd, intgroup = c("Treatment", "Genotype"), returnData = TRUE)
percentVar <- round(100*attr(vst_PCAdata, "percentVar")) 

g1 <- ggplot(vst_PCAdata, aes(PC1, PC2, color=Treatment, shape=Genotype)) +
   geom_point(size=3) +
   xlab(paste0("PC1: ",percentVar[1],"% variance")) +
   ylab(paste0("PC2: ",percentVar[2],"% variance")) +
   ggtitle("A.cervicornis") +
   theme_bw() + #Set background color
   theme(panel.border = element_blank(), # Set border
         axis.line = element_line(colour = "black"), #Set axes color
         plot.background=element_blank()) +
  scale_color_manual(values = c("grey", "#FF3333", "#00CCCC")) 
#ggsave("PCA_allgenets.pdf")
```


# separate genotype and plot treatment for each 

```{r}
#how do i make Vsd something that I can filter?
colData(Vsd)
metadata <- colData(Vsd)

BC_8b <- metadata$Genotype == "BC_8b"
BC_8b <- Vsd[, BC_8b]

vst_PCA_BC8b <- plotPCA(BC_8b, intgroup = c("Treatment"), returnData = TRUE)
percentVar <- round(100*attr(vst_PCA_BC8b, "percentVar")) 
g2 <- ggplot(vst_PCA_BC8b, aes(PC1, PC2, color=Treatment)) + 
   geom_point(size=3) +
   xlab(paste0("PC1: ",percentVar[1],"% variance")) +
   ylab(paste0("PC2: ",percentVar[2],"% variance")) +
   ggtitle("A.cervicornis genet BC-8b") +
   theme_bw() + 
   scale_color_manual(values = c("grey",  "#FF3333", "#00CCCC")) + 
  stat_ellipse(aes(PC1, PC2, group=Treatment, lty = Treatment), type = "norm") 
# there aren't enough samples for this genotype at the final time point for this to be statistically relevant as its own group

MB_B <- metadata$Genotype == "MB_B"
MB_B <- Vsd[, MB_B]

vst_PCA_MB_B<- plotPCA(MB_B, intgroup = c("Treatment"), returnData = TRUE)
percentVar <- round(100*attr(vst_PCA_MB_B, "percentVar")) 
g3 <- ggplot(vst_PCA_MB_B, aes(PC1, PC2, color=Treatment)) + 
   geom_point(size=3) +
   xlab(paste0("PC1: ",percentVar[1],"% variance")) +
   ylab(paste0("PC2: ",percentVar[2],"% variance")) +
   ggtitle("A.cervicornis genet MB-B") +
   theme_bw() + 
   scale_color_manual(values = c("grey",  "#FF3333", "#00CCCC"))  + 
  stat_ellipse(aes(PC1, PC2, group=Treatment, lty = Treatment), type = "norm") 
# this one looks awesome!!!!


SI_C <- metadata$Genotype == "SI_C"
SI_C <- Vsd[, SI_C]

vst_PCA_SI_C<- plotPCA(SI_C, intgroup = c("Treatment"), returnData = TRUE)
percentVar <- round(100*attr(vst_PCA_SI_C, "percentVar")) 
g4 <- ggplot(vst_PCA_SI_C, aes(PC1, PC2, color=Treatment)) + 
   geom_point(size=3) +
   xlab(paste0("PC1: ",percentVar[1],"% variance")) +
   ylab(paste0("PC2: ",percentVar[2],"% variance")) +
   ggtitle("A.cervicornis genet SI-C") +
   theme_bw() + 
   scale_color_manual(values = c("grey",  "#FF3333", "#00CCCC"))  + 
  stat_ellipse(aes(PC1, PC2, group=Treatment, lty = Treatment), type = "norm") 
# this one too!!!!!

combined_plot <- plot_grid(g1, g2, g3, g4, nrow = 2, ncol = 2)
print(combined_plot)
ggsave("combined_PCA_plot.pdf", combined_plot, width = 10, height = 7)
```

# PC axes 2 and 3
```{r}
## functions for PCA axes 2 and 3
#PCA 2 and 3 axis creation
pcaaxes23 = function (object, intgroup = "condition", ntop = 500, returnData = FALSE) 
{
    rv <- rowVars(assay(object))
    select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, 
        length(rv)))]
    pca <- prcomp(t(assay(object)[select, ]))
    percentVar <- pca$sdev^2/sum(pca$sdev^2)
    if (!all(intgroup %in% names(colData(object)))) {
        stop("the argument 'intgroup' should specify columns of colData(dds)")
    }
    intgroup.df <- as.data.frame(colData(object)[, intgroup, 
        drop = FALSE])
    group <- if (length(intgroup) > 1) {
        factor(apply(intgroup.df, 1, paste, collapse = ":"))
    }
    else {
        colData(object)[[intgroup]]
    }
    d <- data.frame(PC2 = pca$x[, 2], PC3 = pca$x[, 3], group = group, 
        intgroup.df, name = colnames(object))
    if (returnData) {
        attr(d, "percentVar") <- percentVar[2:3]
        return(d)
    }
    ggplot(data = d, aes_string(x = "PC2", y = "PC3", color = "group")) + 
        geom_point(size = 3) + xlab(paste0("PC2: ", round(percentVar[2] * 
        100), "% variance")) + ylab(paste0("PC3: ", round(percentVar[3] * 
        100), "% variance")) + coord_fixed()
}
```


```{r}
pca23 <- pcaaxes23(Vsd, intgroup=c("Treatment", "Genotype"), returnData = TRUE)

pcaaxes23(Vsd, intgroup=c("Genotype"), returnData = F)

pcaaxes23(Vsd, intgroup=c("Treatment"), returnData = F)

percentVar_pc23 <- round(100*attr(pca23, "percentVar")) 

ggplot(pca23, aes(PC2, PC3, color=Treatment)) + 
   geom_point(size=3) +
   xlab(paste0("PC2: ",percentVar_pc23[1],"% variance")) +
   ylab(paste0("PC3: ",percentVar_pc23[2],"% variance")) +
   ggtitle("Acervicornis") +
   theme_bw() + 
   scale_color_manual(values = c("grey", "#00CCCC", "#FF3333"))
ggsave("PCA_allgenets_axes23.pdf")
```